import {isIP} from "node:net"
import {lookup} from "node:dns/promises"
import type {AgentProfile} from "../control-plane/types"
import type {CancelResult,ExecutionAdapter,ExecutionArtifact,ExecutionHealth,ExecutionRequest,ExternalRun,ExternalRunSnapshot} from "../execution/types"

export interface HttpAgentConfig {baseUrl:string;credentialRef?:string;submitPath:string;statusPath:string;cancelPath?:string;healthPath:string;requestTimeoutMs:number;pollIntervalMs:number;cancelSupported:boolean}
type Fetch=typeof fetch
const MAX_ARTIFACTS=100,MAX_ARTIFACT_JSON_BYTES=256_000
const privateAddress=(address:string)=>address==="::1"||address.startsWith("fc")||address.startsWith("fd")||address.startsWith("fe80:")||/^127\./.test(address)||/^10\./.test(address)||/^192\.168\./.test(address)||(/^172\.(\d+)\./.test(address)&&Number(address.split(".")[1])>=16&&Number(address.split(".")[1])<=31)||/^169\.254\./.test(address)
const path=(value:unknown,fallback:string)=>{const result=typeof value==="string"?value:fallback;if(!result.startsWith("/")||result.startsWith("//")||result.includes("://"))throw new Error("HTTP_AGENT_INVALID_PATH");return result}
export function parseHttpAgentConfig(profile:AgentProfile):HttpAgentConfig {const c=profile.config,url=new URL(String(c.baseUrl??""));if(!["http:","https:"].includes(url.protocol))throw new Error("HTTP_AGENT_INVALID_SCHEME");if(url.username||url.password)throw new Error("HTTP_AGENT_URL_CREDENTIALS_FORBIDDEN");url.pathname=url.pathname.replace(/\/$/,"");return{baseUrl:url.toString().replace(/\/$/,""),credentialRef:typeof c.credentialRef==="string"?c.credentialRef:undefined,submitPath:path(c.submitPath,"/runs"),statusPath:path(c.statusPath,"/runs/{runId}"),cancelPath:c.cancelPath===null?undefined:path(c.cancelPath,"/runs/{runId}/cancel"),healthPath:path(c.healthPath,"/health"),requestTimeoutMs:Math.min(120_000,Math.max(100,Number(c.requestTimeoutMs??15_000))),pollIntervalMs:Math.min(60_000,Math.max(250,Number(c.pollIntervalMs??2_000))),cancelSupported:c.cancelSupported===false?false:c.cancelPath!==null}}
async function authorizeTarget(config:HttpAgentConfig){const url=new URL(config.baseUrl),allowed=new Set((process.env.HTTP_AGENT_ALLOWED_HOSTS??"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean));if(!allowed.has(url.hostname.toLowerCase()))throw new Error("HTTP_AGENT_HOST_NOT_ALLOWED");if(process.env.HTTP_AGENT_ALLOW_PRIVATE_NETWORKS==="true")return;const addresses=isIP(url.hostname)?[{address:url.hostname}]:await lookup(url.hostname,{all:true});if(addresses.some(item=>privateAddress(item.address)))throw new Error("HTTP_AGENT_PRIVATE_NETWORK_FORBIDDEN")}
const credential=(reference?:string)=>{if(!reference)return undefined;if(!/^env:[A-Z][A-Z0-9_]*$/.test(reference))throw new Error("HTTP_AGENT_INVALID_CREDENTIAL_REF");const value=process.env[reference.slice(4)];if(!value)throw new Error("HTTP_AGENT_CREDENTIAL_UNAVAILABLE");return value}
const runPath=(template:string,id:string)=>template.replace("{runId}",encodeURIComponent(id))
export class HttpExecutionAdapter implements ExecutionAdapter {
  readonly adapterType="http" as const
  constructor(private request:Fetch=fetch){}
  async health(profile:AgentProfile):Promise<ExecutionHealth>{try{const config=parseHttpAgentConfig(profile);await authorizeTarget(config);const response=await this.call(config,config.healthPath,{method:"GET"});return{status:response.ok?"ready":"degraded",metadata:{httpStatus:response.status}}}catch(error){return{status:"unavailable",message:error instanceof Error?error.message:"HTTP agent unavailable"}}}
  async dispatch(input:ExecutionRequest):Promise<ExternalRun>{const config=parseHttpAgentConfig(input.profile);await authorizeTarget(config);const response=await this.call(config,config.submitPath,{method:"POST",headers:{"content-type":"application/json","idempotency-key":input.delegationId},body:JSON.stringify({instruction:input.instruction,taskId:input.taskId,projectId:input.projectId,delegationId:input.delegationId,context:input.context,constraints:input.constraints})});const body=await json(response);if(!response.ok)throw new Error(`HTTP_AGENT_SUBMIT_${response.status}`);const externalRunId=String(body.runId??"");if(!externalRunId)throw new Error("HTTP_AGENT_INVALID_RESPONSE");const now=Date.now();return{id:globalThis.crypto.randomUUID(),delegationId:input.delegationId,provider:"http",externalRunId,providerStatus:String(body.status??"queued"),createdAt:now,updatedAt:now,startedAt:now,metadata:{httpConfig:config,profileId:input.profile.id}}}
  async reconcile(run:ExternalRun):Promise<ExternalRunSnapshot>{const config=this.configForRun(run);await authorizeTarget(config);const response=await this.call(config,runPath(config.statusPath,run.externalRunId),{method:"GET"});if(!response.ok)throw new Error(`HTTP_AGENT_STATUS_${response.status}`);const body=await json(response),status=String(body.status??"");if(!["queued","starting","running","waiting_for_human","succeeded","failed","cancelled"].includes(status))throw new Error("HTTP_AGENT_INVALID_STATUS");const raw=Array.isArray(body.artifacts)?body.artifacts.slice(0,MAX_ARTIFACTS):[];if(Buffer.byteLength(JSON.stringify(raw))>MAX_ARTIFACT_JSON_BYTES)throw new Error("HTTP_AGENT_ARTIFACTS_TOO_LARGE");const artifacts=raw.map((item):Omit<ExecutionArtifact,"id"|"delegationId"|"provider">=>{const artifact=item as Record<string,unknown>;return{type:["diff","file","document","report","log","url","other"].includes(String(artifact.type))?String(artifact.type) as ExecutionArtifact["type"]:"other",label:String(artifact.label??"Artifact").slice(0,300),externalRef:typeof artifact.externalRef==="string"?artifact.externalRef:undefined,url:typeof artifact.url==="string"?artifact.url:undefined}});return{externalRunId:run.externalRunId,status:status==="queued"?"starting":status as ExternalRunSnapshot["status"],providerStatus:status,humanInput:{required:body.requiresHumanInput===true,message:typeof body.inputMessage==="string"?body.inputMessage.slice(0,1000):undefined},artifacts}}
  async cancel(run:ExternalRun):Promise<CancelResult>{const config=this.configForRun(run);if(!config.cancelSupported||!config.cancelPath)return{status:"unsupported",message:"CANCELLATION_NOT_SUPPORTED"};await authorizeTarget(config);const response=await this.call(config,runPath(config.cancelPath,run.externalRunId),{method:"POST"});if(!response.ok)throw new Error(`HTTP_AGENT_CANCEL_${response.status}`);const body=await json(response);return{status:body.status==="cancelled"?"cancelled":"requested"}}
  private configForRun(run:ExternalRun){const config=run.metadata?.httpConfig;if(!config||typeof config!=="object")throw new Error("HTTP_AGENT_RUN_CONFIG_MISSING");return parseHttpAgentConfig({config:config as Record<string,unknown>,id:String(run.metadata?.profileId??""),name:"",adapterType:"http",enabled:true,locality:"remote",capabilities:[],maxConcurrency:1,revision:1,createdAt:0,updatedAt:0})}
  private async call(config:HttpAgentConfig,target:string,init:RequestInit){const token=credential(config.credentialRef),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),config.requestTimeoutMs);try{return await this.request(new URL(target,`${config.baseUrl}/`),{...init,signal:controller.signal,headers:{...(token?{authorization:`Bearer ${token}`}:{}) ,...init.headers}})}finally{clearTimeout(timer)}}
}
async function json(response:Response):Promise<Record<string,unknown>>{const text=await response.text();if(Buffer.byteLength(text)>1_000_000)throw new Error("HTTP_AGENT_RESPONSE_TOO_LARGE");try{return JSON.parse(text) as Record<string,unknown>}catch{throw new Error("HTTP_AGENT_INVALID_JSON")}}
