import type {AgTxBoardChange,AgTxExecutionAdapter,AgTxProject,AgTxRuntimeHealth,AgTxTaskRequest,AgTxTaskSnapshot} from "./types"
import {AGTX_PHASES} from "./types"
import type {AgTxConfig} from "./config"
import {McpJsonRpcClient,StdioMcpTransport} from "./mcp-client"
const obj=(x:unknown):Record<string,unknown>=>x&&typeof x==="object"&&!Array.isArray(x)?x as Record<string,unknown>:{}
const array=(x:unknown):unknown[]=>Array.isArray(x)?x:[]
const value=(o:Record<string,unknown>,...keys:string[])=>keys.map(k=>o[k]).find(v=>v!==undefined)
function task(raw:unknown,projectId=""):AgTxTaskSnapshot{const o=obj(raw),phase=String(value(o,"phase","column","status")??"Backlog");if(!AGTX_PHASES.includes(phase as never))throw new Error("AGTX_INVALID_RESPONSE");return{id:String(value(o,"id","task_id")??""),projectId:String(value(o,"projectId","project_id")??projectId),title:String(value(o,"title","name")??"Untitled"),description:typeof o.description==="string"?o.description:undefined,phase:phase as AgTxTaskSnapshot["phase"],allowedActions:array(value(o,"allowedActions","allowed_actions")).map(String),workflow:typeof o.workflow==="string"?o.workflow:undefined,agent:typeof o.agent==="string"?o.agent:undefined,phaseChangedAt:typeof value(o,"phaseChangedAt","phase_changed_at")==="number"?Number(value(o,"phaseChangedAt","phase_changed_at")):undefined,blocked:o.blocked===true,needsInput:o.needs_input===true||o.needsInput===true,artifacts:array(o.artifacts).map(a=>{const x=obj(a);return{type:String(x.type??"artifact"),label:String(x.label??x.name??"Artifact"),reference:String(x.reference??x.id??"")}}),diffSummary:typeof value(o,"diffSummary","diff_summary")==="string"?String(value(o,"diffSummary","diff_summary")):undefined,outputTail:typeof value(o,"outputTail","output_tail")==="string"?String(value(o,"outputTail","output_tail")).slice(-8000):undefined,failure:obj(o.failure).summary?{code:String(obj(o.failure).code??"AGTX_TASK_FAILED"),summary:String(obj(o.failure).summary).slice(0,1000)}:undefined}}
export class AgTxMcpAdapter implements AgTxExecutionAdapter {constructor(private client:McpJsonRpcClient,private config:AgTxConfig){}static async connect(config:AgTxConfig,projectPath?:string){const args=["mcp-serve",...(config.mode==="project"&&projectPath?[projectPath]:[])],client=new McpJsonRpcClient(new StdioMcpTransport(config.binary,args),config.requestTimeoutMs);await client.initialize();return new AgTxMcpAdapter(client,config)}async health(){try{const projects=await this.listProjects();return{configured:true,binaryAvailable:true,mcpConnected:true,compatible:true,executionEnabled:this.config.executionEnabled,version:this.client.serverVersion,projectCount:projects.length}}catch(e){return{configured:true,binaryAvailable:true,mcpConnected:false,compatible:false,executionEnabled:this.config.executionEnabled,projectCount:0,errorCode:e instanceof Error?e.message:"AGTX_UNAVAILABLE"}}}async listProjects():Promise<AgTxProject[]>{const raw=await this.client.callTool("list_projects"),r=obj(raw),items=array(r.projects??r.items??raw);return items.map(x=>{const p=obj(x);return{id:String(p.id??p.project_id??""),name:String(p.name??p.id??"Project"),repositoryPath:typeof(p.repository_path??p.path)==="string"?String(p.repository_path??p.path):undefined,configured:p.configured===undefined?undefined:p.configured===true}})}async listTasks(projectId?:string){const raw=await this.client.callTool("list_tasks",projectId?{project_id:projectId}:{}),r=obj(raw);return array(r.tasks??r.items??raw).map(x=>task(x,projectId))}async createTask(request:AgTxTaskRequest){const description=`${request.description}\n\nNodepad delegation: ${request.correlationId}`.slice(0,20000),r=obj(await this.client.callTool("create_task",{project_id:request.projectId,title:request.title.slice(0,300),description})),id=String(r.id??r.task_id??obj(r.task).id??"");if(!id)throw new Error("AGTX_INVALID_RESPONSE");return r.task?task(r.task,request.projectId):this.getTask(request.projectId,id)}async getTask(projectId:string,id:string){const r=obj(await this.client.callTool("get_task",{project_id:projectId,task_id:id}));return task(r.task??r,projectId)}async transition(projectId:string,id:string,action:string){const current=await this.getTask(projectId,id);if(!current.allowedActions.includes(action))throw new Error("AGTX_ACTION_NOT_ALLOWED");await this.client.callTool("move_task",{project_id:projectId,task_id:id,action})}async waitForChange(timeoutMs?:number):Promise<AgTxBoardChange>{const r=obj(await this.client.callTool("wait_for_board_change",timeoutMs?{timeout_ms:timeoutMs}:{}));return{changedTaskIds:array(r.changed_task_ids??r.changedTaskIds).map(String),transitionOutcomes:array(r.transition_outcomes??r.transitionOutcomes)}}async findByCorrelation(projectId:string,correlationId:string){return(await this.listTasks(projectId)).find(t=>t.description?.includes(`Nodepad delegation: ${correlationId}`))}async close(){await this.client.close()}}
