import {afterEach,describe,it} from "node:test"
import assert from "node:assert/strict"
import {mkdtempSync,mkdirSync} from "node:fs"
import {tmpdir} from "node:os"
import {join} from "node:path"
import {openDatabase} from "../server/database"
import {WorkspaceRepository} from "../server/workspace-repository"
import {ControlPlaneRepository} from "../server/control-plane-repository"
import {AgTxExecutionRepository} from "../server/agtx-execution-repository"
import {RoutingDecisionRepository} from "../server/routing-decision-repository"
import {createAgentProfile,createDelegationDraft,emptyControlPlane,transitionDelegation} from "../control-plane/operations"
import {AgTxDelegationDispatcher} from "./dispatcher"
import {mapAgTxPhase,type AgTxExecutionAdapter,type AgTxTaskSnapshot} from "./types"
const prior={roots:process.env.AGTX_PROJECT_ROOTS,enabled:process.env.AGTX_EXECUTION_ENABLED};afterEach(()=>{process.env.AGTX_PROJECT_ROOTS=prior.roots;process.env.AGTX_EXECUTION_ENABLED=prior.enabled})
class FakeAdapter implements AgTxExecutionAdapter {creates=0;snapshot:AgTxTaskSnapshot={id:"ext-1",projectId:"ap",title:"Code",phase:"Backlog",allowedActions:["plan"]};unavailable=false;async health(){return{configured:true,binaryAvailable:true,mcpConnected:!this.unavailable,compatible:!this.unavailable,executionEnabled:true,projectCount:1}}async listProjects(){return[]}async listTasks(){return[this.snapshot]}async findByCorrelation(){return this.snapshot}async createTask(){this.creates++;return this.snapshot}async getTask(){if(this.unavailable)throw new Error("offline");return this.snapshot}async transition(_p:string,_t:string,a:string){if(!this.snapshot.allowedActions.includes(a))throw new Error("bad")}async waitForChange(){return{changedTaskIds:[]}}async close(){}}
function setup(){const root=mkdtempSync(join(tmpdir(),"agtx-dispatch-")),repoPath=join(root,"repo");mkdirSync(repoPath);process.env.AGTX_PROJECT_ROOTS=root;process.env.AGTX_EXECUTION_ENABLED="true";const db=openDatabase(":memory:"),workspace={id:"w",name:"W",entities:[{id:"p",type:"project" as const,title:"P",createdAt:1,updatedAt:1},{id:"t",type:"task" as const,title:"Code",body:"Implement safely",createdAt:1,updatedAt:1}],edges:[{id:"e",sourceId:"t",targetId:"p",type:"belongs_to",origin:"user" as const,createdAt:1,updatedAt:1}],collapsedIds:[],ghostNotes:[]};new WorkspaceRepository(db).saveState({version:2,activeWorkspaceId:"w",savedAt:1,workspaces:[workspace]});let s=createAgentProfile(emptyControlPlane(),{name:"AGTX",adapterType:"agtx",enabled:true,locality:"local",capabilities:["code","git"],maxConcurrency:1,config:{controlMode:"mcp"}}),agent=s.agents[0];const audit={decisionId:"decision",selectedAgentId:agent.id,eligibleAgentIds:[agent.id],probabilities:{},decision:"deterministic" as const,decisionSource:"deterministic" as const,filteredAgents:[],matchedRuleIds:[],controlPlaneRevision:0,createdAt:1};new RoutingDecisionRepository(db).saveDecision(audit);s=createDelegationDraft(s,workspace,{taskEntityId:"t",projectEntityId:"p",requestedBy:"user",agentProfileId:agent.id,routingDecisionId:"decision",request:{instruction:"Do the coding work"}});s={...s,agtxMappings:[{id:"m",nodepadProjectEntityId:"p",agentProfileId:agent.id,agtxProjectId:"ap",repositoryPath:repoPath,enabled:true,createdAt:1,updatedAt:1}]};s=new ControlPlaneRepository(db).save(s,0);s=transitionDelegation(s,s.delegations[0].id,"queued");s=new ControlPlaneRepository(db).save(s,s.revision);return{db,id:s.delegations[0].id}}
describe("AGTX dispatcher",()=>{it("requires explicit authorization, dispatches once, and persists external identity/events",async()=>{const{db,id}=setup(),adapter=new FakeAdapter(),dispatcher=new AgTxDelegationDispatcher(db,adapter);await assert.rejects(dispatcher.dispatch(id),/PRECONDITION/);const first=await dispatcher.authorizeAndDispatch(id,"user"),second=await dispatcher.dispatch(id);assert.equal(first.externalRunId,"ext-1");assert.equal(second.idempotent,true);assert.equal(adapter.creates,1);const state=new ControlPlaneRepository(db).load(),d=state.delegations.find(x=>x.id===id)!;assert.equal(d.externalProvider,"agtx");assert.equal(d.externalRunId,"ext-1");const canonical=new WorkspaceRepository(db).loadState()!;assert.throws(()=>new WorkspaceRepository(db).saveState({...canonical,workspaces:canonical.workspaces.map(w=>({...w,entities:w.entities.filter(e=>e.id!=="t"),edges:w.edges.filter(e=>e.sourceId!=="t"&&e.targetId!=="t")}))},{w:canonical.workspaces[0].revision!}),/ACTIVE_AGTX_DELEGATION/);db.close()});it("recovers a response-lost creating attempt by correlation without a duplicate",async()=>{const{db,id}=setup(),adapter=new FakeAdapter(),repo=new AgTxExecutionRepository(db);repo.authorize(id,"user");repo.markCreating(id);const result=await new AgTxDelegationDispatcher(db,adapter).dispatch(id);assert.equal(result.externalRunId,"ext-1");assert.equal(adapter.creates,0);db.close()});it("reconciles phases after a dispatcher restart and preserves unavailable work",async()=>{const{db,id}=setup(),adapter=new FakeAdapter(),first=new AgTxDelegationDispatcher(db,adapter);await first.authorizeAndDispatch(id);for(const [phase,status] of [["Planning","running"],["Running","running"],["Review","review"],["Done","succeeded"]] as const){adapter.snapshot={...adapter.snapshot,phase};const d=await new AgTxDelegationDispatcher(db,adapter).reconcile(id) as {status:string};assert.equal(d.status,status)}assert.equal(new ControlPlaneRepository(db).load().delegations.find(x=>x.id===id)?.taskEntityId,"t");db.close()});it("does not fail active work when AGTX is unavailable and enforces allowed actions",async()=>{const{db,id}=setup(),adapter=new FakeAdapter(),dispatcher=new AgTxDelegationDispatcher(db,adapter);await dispatcher.authorizeAndDispatch(id);await assert.rejects(dispatcher.transition(id,"finish"),/NOT_ALLOWED/);adapter.unavailable=true;const d=await dispatcher.reconcile(id) as {status:string};assert.equal(d.status,"waiting_for_agent");db.close()});it("maps AGTX lifecycle and input state centrally",()=>{assert.equal(mapAgTxPhase({phase:"Backlog"}),"starting");assert.equal(mapAgTxPhase({phase:"Planning"}),"running");assert.equal(mapAgTxPhase({phase:"Running"}),"running");assert.equal(mapAgTxPhase({phase:"Review"}),"review");assert.equal(mapAgTxPhase({phase:"Done"}),"succeeded");assert.equal(mapAgTxPhase({phase:"Running",needsInput:true}),"waiting_for_human")})})
