import {describe,it} from "node:test"
import assert from "node:assert/strict"
import {openDatabase} from "./database"
import {WorkspaceRepository} from "./workspace-repository"
import {ControlPlaneConflictError,ControlPlaneRepository} from "./control-plane-repository"
import {assignAgent,createAgentProfile,createDelegationDraft,createRoutingRule,emptyControlPlane} from "../control-plane/operations"
const workspace={id:"w",name:"W",entities:[{id:"p",type:"project" as const,title:"P",createdAt:1,updatedAt:1},{id:"t",type:"task" as const,title:"T",createdAt:1,updatedAt:1}],edges:[],collapsedIds:[],ghostNotes:[]}
describe("control plane SQLite repository",()=>{
 it("round-trips all records across repository instances with global optimistic revision",()=>{const db=openDatabase(":memory:");new WorkspaceRepository(db).saveState({version:2,activeWorkspaceId:"w",savedAt:1,workspaces:[workspace]});let s=emptyControlPlane();s=createAgentProfile(s,{name:"A",adapterType:"http",enabled:true,locality:"remote",capabilities:["web"],maxConcurrency:1,config:{baseUrl:"https:\/\/a.test",credentialRef:"AGENT_TOKEN"}});s=createRoutingRule(s,{name:"Web",enabled:true,priority:5,match:{requiresWeb:true},route:{agentProfileId:s.agents[0].id}});s=assignAgent(s,workspace,"task","t",s.agents[0].id);s=createDelegationDraft(s,workspace,{taskEntityId:"t",requestedBy:"user",request:{instruction:"Research"}});const saved=new ControlPlaneRepository(db).save(s,0);assert.equal(saved.revision,1);const loaded=new ControlPlaneRepository(db).load();assert.deepEqual([loaded.agents.length,loaded.rules.length,loaded.assignments.length,loaded.delegations.length],[1,1,1,1]);assert.equal((loaded.agents[0].config as Record<string,unknown>).credentialRef,"AGENT_TOKEN");assert.throws(()=>new ControlPlaneRepository(db).save(loaded,0),ControlPlaneConflictError);db.close()})
 it("enforces agent foreign keys and canonical scope references",()=>{const db=openDatabase(":memory:");new WorkspaceRepository(db).saveState({version:2,activeWorkspaceId:"w",savedAt:1,workspaces:[workspace]});const repo=new ControlPlaneRepository(db),s=emptyControlPlane();assert.throws(()=>repo.save({...s,assignments:[{id:"x",scope:"task",scopeId:"t",agentProfileId:"missing",role:"default",createdAt:1,updatedAt:1}]},0),/ASSIGNMENT_INVALID/);db.close()})
 it("rejects delegations created directly in runtime-like states",()=>{const db=openDatabase(":memory:");new WorkspaceRepository(db).saveState({version:2,activeWorkspaceId:"w",savedAt:1,workspaces:[workspace]});const repo=new ControlPlaneRepository(db),s=emptyControlPlane();assert.throws(()=>repo.save({...s,delegations:[{id:"d",taskEntityId:"t",requestedBy:"user",status:"queued",request:{instruction:"Do it"},createdAt:1,updatedAt:1}]},0),/INVALID_DELEGATION_STATE/);db.close()})
})
