import type { DatabaseSync } from "node:sqlite"
import type { ControlPlaneState } from "../control-plane/types"
import { validateControlPlaneState, publicAgent } from "../control-plane/validation"
import { DELEGATION_TRANSITIONS } from "../control-plane/operations"
import {getAgTxConfig,validateRepositoryPathSync} from "../agtx/config"
export class ControlPlaneConflictError extends Error {constructor(public expected:number,public actual:number){super("Control plane changed elsewhere")}}
const parse=<T>(v:unknown):T=>JSON.parse(String(v)) as T
export class ControlPlaneRepository {
 constructor(private db:DatabaseSync){}
 load():ControlPlaneState {const meta=this.db.prepare("SELECT revision FROM control_plane_state WHERE singleton=1").get() as {revision:number}|undefined;return{revision:meta?.revision??0,agents:(this.db.prepare("SELECT payload_json FROM agent_profiles ORDER BY created_at").all() as {payload_json:string}[]).map(x=>publicAgent(parse(x.payload_json))),rules:(this.db.prepare("SELECT payload_json FROM routing_rules ORDER BY priority DESC,id").all() as {payload_json:string}[]).map(x=>parse(x.payload_json)),assignments:(this.db.prepare("SELECT payload_json FROM agent_assignments ORDER BY created_at").all() as {payload_json:string}[]).map(x=>parse(x.payload_json)),delegations:(this.db.prepare("SELECT payload_json FROM delegations ORDER BY created_at DESC").all() as {payload_json:string}[]).map(x=>parse(x.payload_json)),agtxMappings:(this.db.prepare("SELECT payload_json FROM agtx_project_mappings ORDER BY created_at").all() as {payload_json:string}[]).map(x=>parse(x.payload_json))}}
 save(state:ControlPlaneState,expectedRevision:number):ControlPlaneState {if(!validateControlPlaneState(state))throw new Error("INVALID_PAYLOAD");const previous=this.load(),current=previous.revision;if(current!==expectedRevision)throw new ControlPlaneConflictError(expectedRevision,current);this.validateReferences(state);this.validateEvolution(previous,state);this.db.exec("BEGIN IMMEDIATE");try{for(const table of ["agent_assignments","agtx_project_mappings","routing_rules"])this.db.exec(`DELETE FROM ${table}`);const agent=this.db.prepare("INSERT INTO agent_profiles(id,enabled,adapter_type,created_at,updated_at,payload_json) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET enabled=excluded.enabled,adapter_type=excluded.adapter_type,updated_at=excluded.updated_at,payload_json=excluded.payload_json");for(const x of state.agents)agent.run(x.id,x.enabled?1:0,x.adapterType,x.createdAt,x.updatedAt,JSON.stringify(publicAgent(x)));const rule=this.db.prepare("INSERT INTO routing_rules(id,priority,enabled,created_at,updated_at,payload_json) VALUES(?,?,?,?,?,?)");for(const x of state.rules)rule.run(x.id,x.priority,x.enabled?1:0,x.createdAt,x.updatedAt,JSON.stringify(x));const assign=this.db.prepare("INSERT INTO agent_assignments(id,agent_profile_id,scope,scope_id,created_at,updated_at,payload_json) VALUES(?,?,?,?,?,?,?)");for(const x of state.assignments)assign.run(x.id,x.agentProfileId,x.scope,x.scopeId,x.createdAt,x.updatedAt,JSON.stringify(x));const delegation=this.db.prepare("INSERT INTO delegations(id,agent_profile_id,status,created_at,updated_at,payload_json) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET agent_profile_id=excluded.agent_profile_id,status=excluded.status,updated_at=excluded.updated_at,payload_json=excluded.payload_json");for(const x of state.delegations)delegation.run(x.id,x.agentProfileId??null,x.status,x.createdAt,x.updatedAt,JSON.stringify(x));const mapping=this.db.prepare("INSERT INTO agtx_project_mappings(id,nodepad_project_entity_id,agent_profile_id,agtx_project_id,repository_path,enabled,created_at,updated_at,payload_json) VALUES(?,?,?,?,?,?,?,?,?)");for(const x of state.agtxMappings??[])mapping.run(x.id,x.nodepadProjectEntityId,x.agentProfileId,x.agtxProjectId??null,x.repositoryPath,x.enabled?1:0,x.createdAt,x.updatedAt,JSON.stringify(x));this.db.prepare("UPDATE control_plane_state SET revision=? WHERE singleton=1").run(current+1);this.db.exec("COMMIT")}catch(e){this.db.exec("ROLLBACK");throw e}return this.load()}
 private validateReferences(s:ControlPlaneState){const agents=new Set(s.agents.map(a=>a.id)),rules=new Set(s.rules.map(r=>r.id));for(const r of s.rules)for(const id of [r.route.agentProfileId,...(r.route.fallbackAgentProfileIds??[])])if(id&&!agents.has(id))throw new Error("INVALID_ROUTING_RULE");for(const a of s.assignments){if(!agents.has(a.agentProfileId))throw new Error("ASSIGNMENT_INVALID");const row=this.db.prepare("SELECT type FROM entities WHERE id=?").get(a.scopeId) as {type:string}|undefined;if(!row||row.type!==a.scope)throw new Error("ASSIGNMENT_INVALID")}for(const d of s.delegations){if(d.agentProfileId&&!agents.has(d.agentProfileId))throw new Error("AGENT_NOT_FOUND");if(d.routingRuleId&&!rules.has(d.routingRuleId))throw new Error("INVALID_ROUTING_RULE");if(d.taskEntityId&&!this.db.prepare("SELECT 1 FROM entities WHERE id=? AND type='task'").get(d.taskEntityId))throw new Error("ASSIGNMENT_INVALID");if(d.projectEntityId&&!this.db.prepare("SELECT 1 FROM entities WHERE id=? AND type='project'").get(d.projectEntityId))throw new Error("ASSIGNMENT_INVALID")}for(const m of s.agtxMappings??[]){if(!agents.has(m.agentProfileId)||!s.agents.some(a=>a.id===m.agentProfileId&&a.adapterType==="agtx"))throw new Error("AGTX_MAPPING_INVALID");if(!this.db.prepare("SELECT 1 FROM entities WHERE id=? AND type='project'").get(m.nodepadProjectEntityId))throw new Error("AGTX_MAPPING_INVALID");m.repositoryPath=validateRepositoryPathSync(m.repositoryPath,getAgTxConfig().projectRoots)}}
 private validateEvolution(old:ControlPlaneState,next:ControlPlaneState){for(const d of next.delegations){const before=old.delegations.find(x=>x.id===d.id);if(!before&&d.status!=="draft")throw new Error("INVALID_DELEGATION_STATE");if(before&&before.status!==d.status&&!DELEGATION_TRANSITIONS[before.status].includes(d.status))throw new Error("INVALID_DELEGATION_STATE")}}
}
