import type {DatabaseSync} from "node:sqlite"
import type {Delegation,DelegationStatus} from "../control-plane/types"
import type {ExecutionArtifact,ExecutionEvent,ExternalRun} from "../execution/types"
const parse=<T>(value:unknown):T=>JSON.parse(String(value)) as T
const identifier=()=>globalThis.crypto?.randomUUID?.()??Math.random().toString(36).slice(2)
export class ExecutionRepository {
  constructor(private db:DatabaseSync){}
  getRunForDelegation(delegationId:string){let row=this.db.prepare("SELECT * FROM external_runs WHERE delegation_id=?").get(delegationId) as Record<string,unknown>|undefined;if(!row){const legacy=this.db.prepare("SELECT payload_json,created_at,updated_at FROM delegations WHERE id=?").get(delegationId) as {payload_json:string;created_at:number;updated_at:number}|undefined;if(legacy){const delegation=parse<Delegation>(legacy.payload_json);if(delegation.externalRunId&&delegation.externalProvider){const migrated:ExternalRun={id:`migrated-${delegation.id}`,delegationId:delegation.id,provider:delegation.externalProvider,externalRunId:delegation.externalRunId,providerStatus:delegation.lastExternalStatus,createdAt:legacy.created_at,updatedAt:legacy.updated_at,startedAt:delegation.startedAt,finishedAt:delegation.finishedAt,metadata:{migratedFromDelegation:true}};this.createRun(migrated);return migrated}}}return row?this.run(row):undefined}
  createRun(run:ExternalRun){this.db.prepare("INSERT INTO external_runs(id,delegation_id,provider,external_run_id,provider_status,created_at,updated_at,started_at,finished_at,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?)").run(run.id,run.delegationId,run.provider,run.externalRunId,run.providerStatus??null,run.createdAt,run.updatedAt,run.startedAt??null,run.finishedAt??null,JSON.stringify(run.metadata??{}));return run}
  updateRun(run:ExternalRun){this.db.prepare("UPDATE external_runs SET provider_status=?,updated_at=?,started_at=?,finished_at=?,metadata_json=? WHERE id=?").run(run.providerStatus??null,run.updatedAt,run.startedAt??null,run.finishedAt??null,JSON.stringify(run.metadata??{}),run.id);return run}
  addArtifact(artifact:Omit<ExecutionArtifact,"id">){const result={...artifact,id:identifier()};this.db.prepare("INSERT INTO execution_artifacts(id,delegation_id,provider,type,label,external_ref,url,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run(result.id,result.delegationId,result.provider,result.type,result.label,result.externalRef??null,result.url??null,JSON.stringify(result.metadata??{}),Date.now());return result}
  artifacts(delegationId:string){return (this.db.prepare("SELECT * FROM execution_artifacts WHERE delegation_id=? ORDER BY created_at").all(delegationId) as Record<string,unknown>[]).map(row=>({id:String(row.id),delegationId:String(row.delegation_id),provider:String(row.provider),type:String(row.type) as ExecutionArtifact["type"],label:String(row.label),externalRef:row.external_ref?String(row.external_ref):undefined,url:row.url?String(row.url):undefined,metadata:parse<Record<string,unknown>>(row.metadata_json)}))}
  addEvent(event:Omit<ExecutionEvent,"id"|"createdAt">,dedupeKey:string){const id=identifier(),createdAt=Date.now();this.db.prepare("INSERT OR IGNORE INTO delegation_events(id,delegation_id,provider,event_type,external_status,message,metadata_json,dedupe_key,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run(id,event.delegationId,event.provider,event.eventType,event.providerStatus??null,event.message?.slice(0,1000)??null,JSON.stringify(event.metadata??{}),dedupeKey,createdAt);return{id,...event,createdAt}}
  updateDelegation(delegation:Delegation,status:DelegationStatus,run:ExternalRun,diagnostic?:string){const terminal=["succeeded","failed","cancelled"].includes(status),now=Date.now(),next={...delegation,status,externalProvider:run.provider,externalRunId:run.externalRunId,lastExternalStatus:run.providerStatus,runtimeDiagnostic:diagnostic,startedAt:delegation.startedAt??run.startedAt??now,updatedAt:now,...(terminal?{finishedAt:delegation.finishedAt??now}:{})};this.db.prepare("UPDATE delegations SET status=?,updated_at=?,payload_json=? WHERE id=?").run(next.status,next.updatedAt,JSON.stringify(next),next.id);return next}
  private run(row:Record<string,unknown>):ExternalRun{return{id:String(row.id),delegationId:String(row.delegation_id),provider:String(row.provider) as ExternalRun["provider"],externalRunId:String(row.external_run_id),providerStatus:row.provider_status?String(row.provider_status):undefined,createdAt:Number(row.created_at),updatedAt:Number(row.updated_at),startedAt:row.started_at?Number(row.started_at):undefined,finishedAt:row.finished_at?Number(row.finished_at):undefined,metadata:parse(row.metadata_json)}}
}
