import { NextRequest, NextResponse } from "next/server"
import { nodepadService, nodepadStore } from "@/lib/server"
import { runHeartbeat } from "@/lib/heartbeat"
import { backupWorkspace, configuredBackupRemote, stageRestore } from "@/lib/github-sync/backup"
const actor=(r:NextRequest)=>({actorType:(r.headers.get("x-nodepad-actor-type")??"human") as "human"|"agent"|"system",actorId:r.headers.get("x-nodepad-actor-id")??"api-user",role:r.headers.get("x-nodepad-actor-role")??undefined})
const authorized=(r:NextRequest)=>!process.env.NODEPAD_API_KEY||r.headers.get("authorization")===`Bearer ${process.env.NODEPAD_API_KEY}`
const fail=(e:unknown,status=400)=>NextResponse.json({error:e instanceof Error?e.message:String(e)},{status})
export async function GET(req:NextRequest,ctx:{params:Promise<{path:string[]}>}){try{const p=(await ctx.params).path;if(p[0]==="workspaces"&&!p[1])return NextResponse.json(await nodepadService.workspaces());const id=p[1];if(p[2]==="graph")return NextResponse.json(await nodepadService.graph(id));if(p[2]==="context")return NextResponse.json(await nodepadService.context(id));const w=await nodepadStore.getWorkspace(id);if(p[2]==="evidence")return NextResponse.json(w.evidence);if(p[2]==="hypotheses"&&p[3])return NextResponse.json(w.hypotheses.find(h=>h.id===p[3])??null);if(p[2]==="hypotheses")return NextResponse.json(w.hypotheses);if(p[2]==="research"&&p[3]==="tasks")return NextResponse.json(w.researchTasks);if(p[2]==="brain")return NextResponse.json(await nodepadService.brain(id));if(p[2]==="events")return NextResponse.json(w.events);return fail("Unknown API route",404)}catch(e){return fail(e)}}
export async function POST(req:NextRequest,ctx:{params:Promise<{path:string[]}>}){if(!authorized(req))return fail("Unauthorized",401);try{const p=(await ctx.params).path,id=p[1],body=await req.json().catch(()=>({})),key=req.headers.get("idempotency-key")??undefined;if(p[2]==="evidence")return NextResponse.json(await nodepadService.addEvidence(id,body,actor(req),key),{status:201});if(p[2]==="hypotheses")return NextResponse.json(await nodepadService.createHypothesis(id,body,actor(req),key),{status:201});if(p[2]==="syntheses"&&p[3]==="run")return NextResponse.json(await nodepadService.synthesize(id,body.synthesisType,actor(req),body.runId));if(p[2]==="heartbeat")return NextResponse.json(await runHeartbeat(nodepadStore,id,{runId:body.runId,backup:process.env.NODEPAD_GITHUB_SYNC==="true"?configuredBackupRemote():undefined}));if(p[2]==="research"&&p[3]==="tasks"&&p[5]==="results")return NextResponse.json(await nodepadService.submitResearchResult(id,p[4],body,actor(req),key),{status:201});if(p[2]==="brain"&&p[3]==="export")return NextResponse.json(await nodepadService.brain(id));if(p[2]==="github"&&p[3]==="backup"){const w=await nodepadStore.getWorkspace(id);return NextResponse.json(await backupWorkspace(w))}if(p[2]==="github"&&p[3]==="restore"){if(!body.ref)return fail("ref is required");return NextResponse.json(await stageRestore(nodepadStore,configuredBackupRemote(),id,body.ref,body.stagingWorkspaceId))}return fail("Unknown API route",404)}catch(e){return fail(e)}}
