import { requireAuth } from "@/lib/auth/server"
import { NextRequest, NextResponse } from "next/server"
import { nodepadService, nodepadStore } from "@/lib/server"
import { runHeartbeat } from "@/lib/heartbeat"
import { backupWorkspace, configuredBackupRemote, stageRestore } from "@/lib/github-sync/backup"
const actor=(r:NextRequest)=>({actorType:(r.headers.get("x-nodepad-actor-type")??"human") as "human"|"agent"|"system",actorId:r.headers.get("x-nodepad-actor-id")??"api-user",role:r.headers.get("x-nodepad-actor-role")??undefined,sessionId:r.headers.get("x-nodepad-session-id")??undefined,agencyTaskId:r.headers.get("x-agency-task-id")??undefined,correlationId:r.headers.get("x-correlation-id")??undefined})
const fail=(e:unknown,status=400)=>NextResponse.json({error:e instanceof Error?e.message:String(e)},{status})
const revision=(r:NextRequest)=>r.headers.has("if-match")?Number(r.headers.get("if-match")):undefined
async function body(req:NextRequest){const length=Number(req.headers.get("content-length")??0);if(length>1_000_000)throw new Error("request_body_too_large");return req.json().catch(()=>({}))}
export async function GET(req:NextRequest,ctx:{params:Promise<{path:string[]}>}){const denied=requireAuth(req);if(denied)return denied;try{const p=(await ctx.params).path,url=new URL(req.url);if(p[0]==="portfolio")return NextResponse.json(await nodepadService.portfolio());if(p[0]==="workspaces"&&!p[1])return NextResponse.json(await nodepadService.workspaces());const id=p[1];if(p[2]==="graph")return NextResponse.json(await nodepadService.queryGraph(id,{nodeId:url.searchParams.get("nodeId")??undefined,kind:url.searchParams.get("kind")??undefined,depth:Number(url.searchParams.get("depth")??1),qualification:url.searchParams.get("qualification")??undefined,important:url.searchParams.get("important")==="true",stale:url.searchParams.get("stale")==="true",contested:url.searchParams.get("contested")==="true"}));if(p[2]==="context")return NextResponse.json(await nodepadService.context(id));const w=await nodepadStore.getWorkspace(id);if(p[2]==="evidence")return NextResponse.json(w.evidence);if(p[2]==="hypotheses"&&p[3])return NextResponse.json(w.hypotheses.find(h=>h.id===p[3])??null);if(p[2]==="hypotheses")return NextResponse.json(w.hypotheses);if(p[2]==="research"&&p[3]==="tasks")return NextResponse.json(await nodepadService.researchTasks(id,{status:url.searchParams.get("status")??undefined,hypothesisId:url.searchParams.get("hypothesisId")??undefined,objective:url.searchParams.get("objective")??undefined,minPriority:url.searchParams.has("minPriority")?Number(url.searchParams.get("minPriority")):undefined}));if(p[2]==="brain")return NextResponse.json(await nodepadService.brain(id));if(p[2]==="events")return NextResponse.json(w.events);return fail("Unknown API route",404)}catch(e){return fail(e)}}
export async function POST(req:NextRequest,ctx:{params:Promise<{path:string[]}>}){const denied=requireAuth(req);if(denied)return denied;try{const p=(await ctx.params).path,id=p[1],input=await body(req),key=req.headers.get("idempotency-key")??undefined,a=actor(req);if(p[2]==="evidence")return NextResponse.json(await nodepadService.addEvidence(id,input,a,key),{status:201});if(p[2]==="hypotheses")return NextResponse.json(await nodepadService.createHypothesis(id,input,a,key),{status:201});if(p[2]==="syntheses"&&p[3]==="run")return NextResponse.json(await nodepadService.synthesize(id,input.synthesisType,a,input.runId));if(p[2]==="heartbeat")return NextResponse.json(await runHeartbeat(nodepadStore,id,{runId:input.runId,backup:process.env.NODEPAD_GITHUB_SYNC==="true"?configuredBackupRemote():undefined}));if(p[2]==="research"&&p[3]==="tasks"&&!p[4])return NextResponse.json(await nodepadService.createResearchTask(id,input,a,key,revision(req)),{status:201});if(p[2]==="research"&&p[3]==="tasks"&&p[5]==="claim")return NextResponse.json(await nodepadService.claimResearchTask(id,p[4],a,input.ttlMs));if(p[2]==="research"&&p[3]==="tasks"&&p[5]==="results")return NextResponse.json(await nodepadService.submitResearchResult(id,p[4],input,a,key),{status:201});if(p[2]==="events"&&p[3]==="agent")return NextResponse.json(await nodepadService.recordAgentEvent(id,input,a,key,revision(req)),{status:201});if(p[2]==="brain"&&p[3]==="export")return NextResponse.json(await nodepadService.brain(id));if(p[2]==="github"&&p[3]==="backup"){const w=await nodepadStore.getWorkspace(id),result=await backupWorkspace(w);w.backup={lastCommitSha:result.commitSha,lastBackupAt:new Date().toISOString(),status:result.conflict?"sync_conflict":result.skipped?"clean":"completed",snapshotHash:result.snapshotHash};await nodepadStore.saveWorkspace(w);return NextResponse.json(result)}if(p[2]==="github"&&p[3]==="restore"){if(!input.ref)return fail("ref is required");return NextResponse.json(await stageRestore(nodepadStore,configuredBackupRemote(),id,input.ref,input.stagingWorkspaceId))}return fail("Unknown API route",404)}catch(e){const message=e instanceof Error?e.message:"";return fail(e,message.startsWith("revision_conflict")?409:400)}}
