import {describe,it} from "node:test"
import assert from "node:assert/strict"
import type {Workspace} from "../domain/workspace"
import {createProject,createTask} from "../projects/operations"
import {assignAgent,createAgentProfile,createDelegationDraft,createRoutingRule,disableAgentProfile,emptyControlPlane,removeAssignment,transitionDelegation,updateAgentProfile} from "./operations"
import {evaluateRoutingPolicy,getMatchingRules} from "./routing"
import {publicAgent} from "./validation"
const base=():Workspace=>({id:"w",name:"W",entities:[],edges:[],collapsedIds:[],ghostNotes:[]})
const profile=(s=emptyControlPlane(),name="Local",caps:("code"|"file_write"|"web")[]=["code"],locality:"local"|"remote"="local")=>createAgentProfile(s,{name,adapterType:"local_cli",enabled:true,locality,capabilities:caps,maxConcurrency:1,config:{commandProfileId:name.toLowerCase()}})
describe("control-plane domain",()=>{
 it("creates, updates, and disables validated profiles",()=>{let s=profile();const a=s.agents[0];s=updateAgentProfile(s,a.id,{name:"Changed"},a.revision);assert.equal(s.agents[0].revision,2);s=disableAgentProfile(s,a.id,2);assert.equal(s.agents[0].enabled,false);assert.throws(()=>createAgentProfile(s,{name:"Bad",adapterType:"local_cli",enabled:true,locality:"local",capabilities:["code"],maxConcurrency:1,config:{command:"rm -rf /"}}),/INVALID_AGENT_CONFIG/);assert.throws(()=>createAgentProfile(s,{name:"Bad",adapterType:"http",enabled:true,locality:"remote",capabilities:["made_up" as never],maxConcurrency:1,config:{baseUrl:"https:\/\/x"}}),/INVALID_AGENT_CONFIG/)})
 it("defensively strips secret values while retaining credential references",()=>{const a=profile().agents[0];assert.deepEqual(publicAgent({...a,config:{commandProfileId:"known",token:"secret",credentialRef:"SAFE_REF"}}).config,{commandProfileId:"known",credentialRef:"SAFE_REF"})})
 it("assigns project and task records separately from graph and validates references",()=>{let w=createProject(base(),{title:"P"});const p=w.entities.at(-1)!;w=createTask(w,{title:"T"},p.id);const t=w.entities.at(-1)!;let s=profile();const a=s.agents[0];s=assignAgent(s,w,"project",p.id,a.id);s=assignAgent(s,w,"task",t.id,a.id);assert.equal(w.entities.some(e=>"agentId" in e),false);assert.equal(evaluateRoutingPolicy(s,{taskEntityId:t.id,projectEntityId:p.id,requiresCode:true}).explicitAssignment?.scope,"task");s=removeAssignment(s,s.assignments.find(x=>x.scope==="task")!.id);assert.equal(evaluateRoutingPolicy(s,{taskEntityId:t.id,projectEntityId:p.id,requiresCode:true}).explicitAssignment?.scope,"project");assert.throws(()=>assignAgent(s,w,"task","missing",a.id),/ASSIGNMENT_INVALID/)})
 it("orders matching rules deterministically and applies hard capability, locality, privacy, and disabled filters",()=>{let s=profile();const local=s.agents[0];s=createAgentProfile(s,{name:"Remote",adapterType:"http",enabled:true,locality:"remote",privacyClass:"public",capabilities:["web"],maxConcurrency:1,config:{baseUrl:"https:\/\/example.test"}});s=createRoutingRule(s,{name:"low",enabled:true,priority:1,match:{requiresCode:true},route:{}});s=createRoutingRule(s,{name:"high",enabled:true,priority:10,match:{requiresCode:true},route:{agentProfileId:local.id}});s=createRoutingRule(s,{name:"off",enabled:false,priority:99,match:{requiresCode:true},route:{}});assert.deepEqual(getMatchingRules(s.rules,{requiresCode:true}).map(x=>x.name),["high","low"]);const r=evaluateRoutingPolicy(s,{requiresCode:true,localityRequirement:"local"});assert.equal(r.selectedAgentId,local.id);assert.ok(r.filteredAgents.some(x=>x.reasons.includes("locality:remote")));s=disableAgentProfile(s,local.id);assert.equal(evaluateRoutingPolicy(s,{requiresCode:true,localityRequirement:"local"}).eligibleAgentIds.length,0)})
 it("leaves multiple candidates unresolved for future Laya and excludes Hermes",()=>{let s=profile();s=profile(s,"Second");s=createAgentProfile(s,{name:"Hermes",adapterType:"hermes",enabled:true,locality:"remote",supervisor:true,capabilities:["planning"],maxConcurrency:1,config:{endpoint:"https:\/\/hermes.test",supervisor:true}});const r=evaluateRoutingPolicy(s,{requiresCode:true});assert.equal(r.eligibleAgentIds.length,2);assert.equal(r.selectedAgentId,undefined);assert.ok(r.filteredAgents.some(x=>x.reasons.includes("supervisor_only")))})
 it("creates, queues and cancels a non-executing delegation",()=>{const w=createTask(base(),{title:"T"}),task=w.entities[0];let s=profile();s=createDelegationDraft(s,w,{taskEntityId:task.id,requestedBy:"user",agentProfileId:s.agents[0].id,request:{instruction:"Review this task",contextEntityIds:[task.id]}});const d=s.delegations[0];assert.equal(d.taskEntityId,task.id);s=transitionDelegation(s,d.id,"queued");s=transitionDelegation(s,d.id,"cancelled");assert.equal(s.delegations[0].status,"cancelled");assert.throws(()=>transitionDelegation(s,d.id,"queued"),/INVALID_DELEGATION_STATE/)})
})
