import type { Workspace } from "../domain/workspace"
import { validateAgentProfile, validateRoutingRule } from "./validation"
import type { AgentAssignment, AgentProfile, ControlPlaneState, Delegation, RoutingRule } from "./types"
const id=()=>globalThis.crypto?.randomUUID?.()??Math.random().toString(36).slice(2), now=()=>Date.now()
export const emptyControlPlane=():ControlPlaneState=>({revision:0,agents:[],rules:[],assignments:[],delegations:[],agtxMappings:[]})
export function createAgentProfile(s:ControlPlaneState,input:Omit<AgentProfile,"id"|"revision"|"createdAt"|"updatedAt">):ControlPlaneState{const t=now(),p={...input,id:id(),revision:1,createdAt:t,updatedAt:t};const e=validateAgentProfile(p);if(e.length)throw new Error(`INVALID_AGENT_CONFIG:${e.join(",")}`);return{...s,agents:[...s.agents,p]}}
export function updateAgentProfile(s:ControlPlaneState,id_:string,patch:Partial<Omit<AgentProfile,"id"|"createdAt">>,expectedRevision?:number):ControlPlaneState{const old=s.agents.find(x=>x.id===id_);if(!old)throw new Error("AGENT_NOT_FOUND");if(expectedRevision!==undefined&&old.revision!==expectedRevision)throw new Error("REVISION_CONFLICT");const p={...old,...patch,id:id_,createdAt:old.createdAt,revision:old.revision+1,updatedAt:now()};const e=validateAgentProfile(p);if(e.length)throw new Error(`INVALID_AGENT_CONFIG:${e.join(",")}`);return{...s,agents:s.agents.map(x=>x.id===id_?p:x)}}
export const disableAgentProfile=(s:ControlPlaneState,id_:string,revision?:number)=>updateAgentProfile(s,id_,{enabled:false},revision)
export function createRoutingRule(s:ControlPlaneState,input:Omit<RoutingRule,"id"|"revision"|"createdAt"|"updatedAt">):ControlPlaneState{const t=now(),r={...input,id:id(),revision:1,createdAt:t,updatedAt:t};const e=validateRoutingRule(r);if(e.length)throw new Error(`INVALID_ROUTING_RULE:${e.join(",")}`);return{...s,rules:[...s.rules,r]}}
export function updateRoutingRule(s:ControlPlaneState,id_:string,patch:Partial<Omit<RoutingRule,"id"|"createdAt">>,expectedRevision?:number):ControlPlaneState{const old=s.rules.find(x=>x.id===id_);if(!old)throw new Error("INVALID_ROUTING_RULE:not_found");if(expectedRevision!==undefined&&old.revision!==expectedRevision)throw new Error("REVISION_CONFLICT");const r={...old,...patch,id:id_,createdAt:old.createdAt,revision:old.revision+1,updatedAt:now()};const e=validateRoutingRule(r);if(e.length)throw new Error(`INVALID_ROUTING_RULE:${e.join(",")}`);return{...s,rules:s.rules.map(x=>x.id===id_?r:x)}}
export const deleteRoutingRule=(s:ControlPlaneState,id_:string):ControlPlaneState=>({...s,rules:s.rules.filter(x=>x.id!==id_),delegations:s.delegations.map(d=>d.routingRuleId===id_?{...d,routingRuleId:undefined}:d)})
export function assignAgent(s:ControlPlaneState,w:Workspace,scope:"project"|"task",scopeId:string,agentProfileId:string,role:AgentAssignment["role"]="default"):ControlPlaneState{const e=w.entities.find(x=>x.id===scopeId&&x.type===scope);if(!e||!s.agents.some(x=>x.id===agentProfileId))throw new Error("ASSIGNMENT_INVALID");const t=now(),same=s.assignments.find(x=>x.scope===scope&&x.scopeId===scopeId&&x.role===role),a:AgentAssignment={id:same?.id??id(),scope,scopeId,agentProfileId,role,createdAt:same?.createdAt??t,updatedAt:t};return{...s,assignments:[...s.assignments.filter(x=>x.id!==a.id),a]}}
export const removeAssignment=(s:ControlPlaneState,id_:string):ControlPlaneState=>({...s,assignments:s.assignments.filter(x=>x.id!==id_)})
export function createDelegationDraft(s:ControlPlaneState,w:Workspace,input:Omit<Delegation,"id"|"status"|"createdAt"|"updatedAt">):ControlPlaneState{if(input.taskEntityId&&!w.entities.some(e=>e.id===input.taskEntityId&&e.type==="task"))throw new Error("ASSIGNMENT_INVALID");if(input.projectEntityId&&!w.entities.some(e=>e.id===input.projectEntityId&&e.type==="project"))throw new Error("ASSIGNMENT_INVALID");if(input.agentProfileId&&!s.agents.some(a=>a.id===input.agentProfileId))throw new Error("AGENT_NOT_FOUND");if(!input.request.instruction?.trim())throw new Error("INVALID_PAYLOAD");const t=now(),d:Delegation={...input,id:id(),status:"draft",createdAt:t,updatedAt:t};return{...s,delegations:[...s.delegations,d]}}
export const DELEGATION_TRANSITIONS:Record<Delegation["status"],Delegation["status"][]>={draft:["queued","cancelled"],queued:["starting","cancelled"],starting:["running","waiting_for_agent","failed"],running:["waiting_for_agent","waiting_for_human","review","failed","cancelled"],waiting_for_agent:["running","waiting_for_human","failed","cancelled"],waiting_for_human:["running","review","failed","cancelled"],review:["running","succeeded","failed","cancelled"],succeeded:[],failed:[],cancelled:[]}
export function transitionDelegation(s:ControlPlaneState,id_:string,status:Delegation["status"]):ControlPlaneState{const d=s.delegations.find(x=>x.id===id_);if(!d)throw new Error("INVALID_DELEGATION_STATE:not_found");if(status==="cancelled"&&d.externalProvider==="agtx"&&d.externalRunId)throw new Error("AGTX_CANCELLATION_UNSUPPORTED");if(d.status!==status&&!DELEGATION_TRANSITIONS[d.status].includes(status))throw new Error("INVALID_DELEGATION_STATE");const terminal=["succeeded","failed","cancelled"].includes(status);return{...s,delegations:s.delegations.map(x=>x.id===id_?{...x,status,updatedAt:now(),...(status==="running"&&!x.startedAt&&{startedAt:now()}),...(terminal&&{finishedAt:now()})}:x)}}
