import { AGENT_ADAPTER_TYPES, AGENT_CAPABILITIES, DELEGATION_STATUSES, type AgentAdapterDefinition, type AgentProfile, type ControlPlaneState, type RoutingRule } from "./types"

const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v)
const str=(v:unknown)=>typeof v==="string"&&v.trim().length>0
const url=(v:unknown)=>{if(!str(v))return false;try{const u=new URL(v as string);return u.protocol==="http:"||u.protocol==="https:"}catch{return false}}
const allowed=(config:Record<string,unknown>,keys:string[])=>Object.keys(config).filter(k=>!keys.includes(k)).map(k=>`unsupported:${k}`)
const credential=(v:unknown)=>v===undefined||/^[A-Z][A-Z0-9_]*$/.test(String(v))

export const ADAPTER_DEFINITIONS:Record<AgentProfile["adapterType"],AgentAdapterDefinition>={
 http:{type:"http",validateConfig:c=>[...allowed(c,["baseUrl","credentialRef","healthPath","timeoutMs"]),...(!url(c.baseUrl)?["baseUrl"]:[]),...(!credential(c.credentialRef)?["credentialRef"]:[])],describeCapabilities:p=>p.capabilities},
 openai_compatible:{type:"openai_compatible",validateConfig:c=>[...allowed(c,["baseUrl","model","credentialRef"]),...(!url(c.baseUrl)?["baseUrl"]:[]),...(!str(c.model)?["model"]:[]),...(!credential(c.credentialRef)?["credentialRef"]:[])],describeCapabilities:p=>p.capabilities},
 local_cli:{type:"local_cli",validateConfig:c=>[...allowed(c,["commandProfileId","workingDirectoryStrategy","timeoutMs"]),...(!str(c.commandProfileId)?["commandProfileId"]:[])],describeCapabilities:p=>p.capabilities},
 agtx:{type:"agtx",validateConfig:c=>[...allowed(c,["controlMode","projectMapping"]),...(c.controlMode!=="mcp"?["controlMode"]:[])],describeCapabilities:p=>p.capabilities},
 hermes:{type:"hermes",validateConfig:c=>[...allowed(c,["endpoint","credentialRef","supervisor"]),...(!url(c.endpoint)?["endpoint"]:[]),...(c.supervisor!==true?["supervisor"]:[]),...(!credential(c.credentialRef)?["credentialRef"]:[])],describeCapabilities:p=>p.capabilities},
}
export function validateAgentProfile(profile:AgentProfile):string[]{const errors:string[]=[];if(!str(profile.id)||!str(profile.name))errors.push("identity");if(!AGENT_ADAPTER_TYPES.includes(profile.adapterType))errors.push("adapterType");if(!["local","remote"].includes(profile.locality))errors.push("locality");if(!Number.isInteger(profile.maxConcurrency)||profile.maxConcurrency<1)errors.push("maxConcurrency");if(!Array.isArray(profile.capabilities)||profile.capabilities.some(c=>!AGENT_CAPABILITIES.includes(c)))errors.push("capabilities");if(!object(profile.config))errors.push("config");else if(ADAPTER_DEFINITIONS[profile.adapterType])errors.push(...ADAPTER_DEFINITIONS[profile.adapterType].validateConfig(profile.config));if(profile.adapterType==="local_cli"&&profile.locality!=="local")errors.push("local_cli:locality");if(profile.adapterType==="hermes"&&!profile.supervisor)errors.push("hermes:supervisor");return [...new Set(errors)]}
export function validateRoutingRule(rule:RoutingRule):string[]{const e:string[]=[];if(!str(rule.id)||!str(rule.name)||!Number.isInteger(rule.priority))e.push("identity");if(rule.match.requiredCapabilities?.some(c=>!AGENT_CAPABILITIES.includes(c)))e.push("capabilities");if(rule.match.locality&&!['local','remote','any'].includes(rule.match.locality))e.push("locality");return e}
export function validateControlPlaneState(v:unknown):v is ControlPlaneState {if(!object(v)||!Number.isInteger(v.revision)||!Array.isArray(v.agents)||!Array.isArray(v.rules)||!Array.isArray(v.assignments)||!Array.isArray(v.delegations)||(v.agtxMappings!==undefined&&!Array.isArray(v.agtxMappings)))return false;return v.agents.every(a=>validateAgentProfile(a as AgentProfile).length===0)&&v.rules.every(r=>validateRoutingRule(r as RoutingRule).length===0)&&v.assignments.every(a=>object(a)&&str(a.id)&&["project","task"].includes(String(a.scope))&&str(a.scopeId)&&str(a.agentProfileId)&&["default","coding","research","file","review","custom"].includes(String(a.role)))&&v.delegations.every(d=>object(d)&&str(d.id)&&DELEGATION_STATUSES.includes(d.status as never)&&["user","hermes","system"].includes(String(d.requestedBy))&&object(d.request)&&str(d.request.instruction))}
export function publicAgent(profile:AgentProfile):AgentProfile {const forbidden=["apiKey","token","secret","password"];const config=Object.fromEntries(Object.entries(profile.config).filter(([k])=>!forbidden.includes(k)));return {...profile,config}}
