import { KNOWLEDGE_EDGE_TYPES, KNOWLEDGE_NODE_KINDS, type Workspace } from "../domain/types"
import { qualificationForScore, scoreHypothesis } from "../scoring/hypothesis"
export interface ValidationResult { valid:boolean; errors:string[] }
export function validateWorkspace(w:Workspace):ValidationResult { const errors:string[]=[]; const ids=new Set(w.nodes.map(n=>n.id)); for(const n of w.nodes){if(!KNOWLEDGE_NODE_KINDS.includes(n.kind))errors.push(`node ${n.id}: invalid kind`);if(!n.provenance?.origin)errors.push(`node ${n.id}: missing provenance`)} for(const e of w.edges){if(!ids.has(e.sourceId)||!ids.has(e.targetId))errors.push(`edge ${e.id}: unresolved endpoint`);if(!KNOWLEDGE_EDGE_TYPES.includes(e.type))errors.push(`edge ${e.id}: invalid type`);if(!e.provenance)errors.push(`edge ${e.id}: missing provenance`)} const evid=new Set(w.evidence.map(e=>e.id)); for(const h of w.hypotheses){for(const id of [...h.supportingEvidence,...h.contradictingEvidence])if(!evid.has(id))errors.push(`hypothesis ${h.id}: missing evidence ${id}`);if(h.qualification!==qualificationForScore(h.evidenceScore))errors.push(`hypothesis ${h.id}: qualification mismatch`);const recomputed=scoreHypothesis(h,w.evidence,Date.parse(h.lastEvaluatedAt??w.updatedAt));if(recomputed.evidenceScore!==h.evidenceScore)errors.push(`hypothesis ${h.id}: score mismatch`);if(h.promoted&&recomputed.confidence<70)errors.push(`hypothesis ${h.id}: low-confidence brain promotion`)} return {valid:!errors.length,errors} }
export const validateNode=(n:unknown)=>Boolean(n&&typeof n==="object"&&"id" in n&&"provenance" in n)
export const validateEdge=validateNode, validateEvidence=validateNode, validateTheme=validateNode, validateSynthesis=validateNode, validateHypothesis=validateNode, validateExperiment=validateNode, validateDecision=validateNode
export const validateBrainPromotion=(w:Workspace)=>validateWorkspace(w)
export const validateGitSnapshot=(w:Workspace)=>validateWorkspace(w)
export const validateWorkflowContracts=(w:Workspace)=>validateWorkspace(w)
