import { KNOWLEDGE_EDGE_TYPES, KNOWLEDGE_NODE_KINDS, type EvidenceRecord, type HypothesisRecord, type KnowledgeEdge, type KnowledgeNode, type SynthesisResult, type Workspace } from "../domain/types"
import { canPromote, qualificationForScore, scoreHypothesis } from "../scoring/hypothesis"
export interface ValidationResult { valid:boolean; errors:string[] }
const result=(errors:string[]):ValidationResult=>({valid:errors.length===0,errors})
export function validateNode(n:KnowledgeNode){const e:string[]=[];if(!n?.id)e.push("node id required");if(!KNOWLEDGE_NODE_KINDS.includes(n?.kind))e.push("invalid node kind");if(!n?.workspaceId)e.push("workspace required");if(!n?.title)e.push("title required");if(!n?.provenance?.origin||!n.provenance.createdAt)e.push("provenance required");if(!Number.isInteger(n?.version)||n.version<1)e.push("positive version required");return result(e)}
export function validateEdge(e:KnowledgeEdge,nodeIds?:Set<string>){const x:string[]=[];if(!e?.id||!e.sourceId||!e.targetId)x.push("edge identity/endpoints required");if(!KNOWLEDGE_EDGE_TYPES.includes(e?.type))x.push("invalid edge type");if(e.sourceId===e.targetId)x.push("self edge prohibited");if(nodeIds&&(!nodeIds.has(e.sourceId)||!nodeIds.has(e.targetId)))x.push("unresolved endpoint");if(!e?.provenance?.origin)x.push("edge provenance required");return result(x)}
export function validateEvidence(e:EvidenceRecord){const x:string[]=[];if(!e.id||!e.workspaceId||!e.claim.trim())x.push("evidence identity/claim required");if(!Number.isInteger(e.strength)||e.strength<1||e.strength>5)x.push("strength must be 1..5");if(!Number.isFinite(e.weight)||e.weight<0)x.push("non-negative weight required");if(!e.sourceType)x.push("source type required");if(!e.ingestedAt||!e.provenance?.origin)x.push("evidence provenance required");return result(x)}
export function validateTheme(n:KnowledgeNode){const x=validateNode(n).errors;if(n.kind!=="theme")x.push("theme kind required");if(typeof n.metadata.clusterKey!=="string")x.push("clusterKey required");return result(x)}
export function validateSynthesis(s:SynthesisResult){const x:string[]=[];if(!/^S\d{3}$/.test(s.synthesisType))x.push("invalid synthesis type");if(!s.inputHash||!s.runId||!s.provenance?.origin)x.push("hash/run/provenance required");if(!Array.isArray(s.derivedFrom)||!Array.isArray(s.unknowns)||!Array.isArray(s.generatedHypotheses))x.push("synthesis arrays required");if(s.generationConfidence<0||s.generationConfidence>100)x.push("generation confidence out of range");return result(x)}
export function validateHypothesis(h:HypothesisRecord){const x:string[]=[];if(!h.id||!h.statement.trim()||!h.hypothesisType)x.push("hypothesis identity/statement/type required");if(h.evidenceScore< -100||h.evidenceScore>100)x.push("score out of range");if(h.confidence<0||h.confidence>100)x.push("confidence out of range");if(h.qualification!==qualificationForScore(h.evidenceScore))x.push("qualification mismatch");return result(x)}
export function validateExperiment(n:KnowledgeNode){const x=validateNode(n).errors;if(n.kind!=="experiment")x.push("experiment kind required");if(!n.metadata.threshold&&!n.metadata.passThreshold)x.push("experiment threshold required");return result(x)}
export function validateDecision(n:KnowledgeNode){const x=validateNode(n).errors;if(n.kind!=="decision")x.push("decision kind required");if(!n.metadata.rationale)x.push("decision rationale required");return result(x)}
export function validateBrainPromotion(w:Workspace){const x:string[]=[];for(const h of w.hypotheses.filter(h=>w.brain.promotedIds.includes(h.id)))if(!canPromote(h))x.push(`${h.id}: promotion gates not met`);return result(x)}
export function validateWorkspace(w:Workspace):ValidationResult{const errors:string[]=[];if(w.schemaVersion!==1)errors.push("unsupported schema");const ids=new Set(w.nodes.map(n=>n.id));for(const n of w.nodes)errors.push(...validateNode(n).errors.map(e=>`node ${n.id}: ${e}`));for(const e of w.edges)errors.push(...validateEdge(e,ids).errors.map(x=>`edge ${e.id}: ${x}`));const evid=new Set(w.evidence.map(e=>e.id));for(const e of w.evidence)errors.push(...validateEvidence(e).errors.map(x=>`evidence ${e.id}: ${x}`));for(const h of w.hypotheses){errors.push(...validateHypothesis(h).errors.map(x=>`hypothesis ${h.id}: ${x}`));for(const id of[...h.supportingEvidence,...h.contradictingEvidence])if(!evid.has(id))errors.push(`hypothesis ${h.id}: missing evidence ${id}`);const recomputed=scoreHypothesis(h,w.evidence,Date.parse(h.lastEvaluatedAt??w.updatedAt));if(recomputed.evidenceScore!==h.evidenceScore)errors.push(`hypothesis ${h.id}: score mismatch`)}for(const s of w.syntheses)errors.push(...validateSynthesis(s).errors.map(x=>`synthesis ${s.id}: ${x}`));errors.push(...validateBrainPromotion(w).errors);return result(errors)}
export const validateGitSnapshot=(w:Workspace)=>validateWorkspace(w)
export function validateWorkflowContracts(w:Workspace){const x:string[]=[];for(const t of w.researchTasks){if(!t.question||!t.objective||!Array.isArray(t.hypothesisIds))x.push(`task ${t.id}: invalid contract`);if(t.attempts>t.maxAttempts)x.push(`task ${t.id}: attempts exceeded`)}return result(x)}
