import { stableId } from "../domain/id"
import type { KnowledgeNode, Workspace } from "../domain/types"
export type GardenerProposalType = "counter_hypothesis"|"alternative_explanation"|"discriminating_test"|"second_order"|"third_order_consequence"|"cross_cluster_bridge"|"hidden_common_cause"|"opportunity"|"new_venture"|"unsupported_proposition"|"experiment_propagation"|"foundational_drift"|"stale_central_knowledge"|"research_gap"|"segment_split"|"weak_central_assumption"|"unexplained_evidence"
export interface GardenerProposal { id:string; type:GardenerProposalType; title:string; rationale:string; relatedIds:string[]; suggestedKind?:KnowledgeNode["kind"] }
export function garden(w:Workspace):GardenerProposal[]{
 const out:GardenerProposal[]=[],seen=new Set<string>();const push=(type:GardenerProposalType,title:string,rationale:string,ids:string[],suggestedKind?:KnowledgeNode["kind"])=>{const id=stableId("garden",w.id,type,...[...ids].sort());if(!seen.has(id)){seen.add(id);out.push({id,type,title,rationale,relatedIds:ids,suggestedKind})}}
 const degree=new Map<string,number>();for(const e of w.edges){degree.set(e.sourceId,(degree.get(e.sourceId)??0)+1);degree.set(e.targetId,(degree.get(e.targetId)??0)+1)}
 for(const h of w.hypotheses){
  if(h.strategicImportance>=60&&!h.alternativeHypotheses.length){push("counter_hypothesis","Propose a counter-hypothesis",`${h.id} is important but has no explicit falsifiable alternative.`,[h.id],"counter_hypothesis");push("alternative_explanation","Find a competing explanation",`Generate a different causal explanation for the observations behind ${h.id}.`,[h.id],"counter_hypothesis")}
  if(h.alternativeHypotheses.length)push("discriminating_test","Design a discriminating test",`Separate ${h.id} from ${h.alternativeHypotheses.join(", ")} using divergent predictions.`,[h.id,...h.alternativeHypotheses],"experiment")
  if(h.evidenceScore>=30){push("second_order","Derive a second-order hypothesis",`If ${h.id} is true, identify the next observable consequence.`,[h.id],"hypothesis");if(h.evidenceScore>=70)push("third_order_consequence","Derive a business consequence",`Trace ${h.id} through a second-order effect to an operational or economic implication.`,[h.id],"hypothesis")}
  if(h.strategicImportance>=60&&h.confidence<50)push("research_gap","Research a high-impact uncertainty",`High importance (${h.strategicImportance}) but confidence ${h.confidence}.`,[h.id],"research_task")
  if(h.promoted&&h.overlays.includes("stale"))push("stale_central_knowledge","Refresh stale central knowledge","Promoted knowledge is stale and should be re-tested.",[h.id],"research_task")
  if(h.promoted&&h.contradictingEvidence.length&&(degree.get(h.id)??0)>=2)push("foundational_drift","Investigate foundational belief drift",`New contradiction affects a promoted belief with downstream dependencies.`,[h.id,...h.contradictingEvidence],"risk")
  if(h.sourceDiversity<2&&/\b(all|every|always)\b/i.test(h.statement))push("segment_split","Check segment over-generalization","Broad claim rests on insufficient source diversity.",[h.id],"segment")
  if(["value_proposition","positioning","pricing"].includes(h.hypothesisType)&&h.supportingEvidence.length<2)push("unsupported_proposition","Ground an unsupported proposition",`${h.hypothesisType} lacks diverse direct support.`,[h.id],"research_task")
 }
 const assumptions=new Map<string,string[]>();for(const h of w.hypotheses)for(const a of h.dependentAssumptions)assumptions.set(a,[...(assumptions.get(a)??[]),h.id]);for(const[a,ids]of assumptions)if(ids.length>1)push("weak_central_assumption","Pressure-test a shared assumption",`${ids.length} hypotheses depend on ${a}.`,[a,...ids],"assumption")
 const themes=w.nodes.filter(n=>n.kind==="theme");if(themes.length>=2){push("cross_cluster_bridge","Find an unspoken bridge",`Test a non-obvious dependency, tension or inversion between ${themes[0].title} and ${themes[1].title}.`,[themes[0].id,themes[1].id],"insight");push("hidden_common_cause","Test a hidden common cause","One latent cause may explain multiple otherwise separate clusters.",[themes[0].id,themes[1].id],"hypothesis");push("opportunity","Explore an adjacent opportunity","Separate clusters may imply a new segment, service, product or distribution wedge.",[themes[0].id,themes[1].id],"opportunity");if(themes.length>=3)push("new_venture","Assess a distinct venture candidate","Multiple clusters may define a distinct customer/problem/value system rather than a feature.",themes.slice(0,3).map(t=>t.id),"opportunity")}
 for(const e of w.evidence){const linked=w.hypotheses.some(h=>[...h.supportingEvidence,...h.contradictingEvidence].includes(e.id));if(!linked&&e.strength>=4)push("unexplained_evidence","Explain strong evidence","Strong evidence has no explaining hypothesis.",[e.id],"hypothesis")}
 for(const n of w.nodes.filter(n=>n.kind==="result")){const propagated=w.edges.some(e=>e.sourceId===n.id&&e.type==="produced")&&w.edges.some(e=>e.type==="supports"||e.type==="contradicts");if(!propagated)push("experiment_propagation","Propagate an experiment result","A result has not been incorporated into a hypothesis.",[n.id],"research_task")}
 return out
}
export function proposalsAsNodes(w:Workspace,p:GardenerProposal[],runId:string):KnowledgeNode[]{const at=new Date().toISOString();return p.map(x=>({id:x.id,workspaceId:w.id,kind:x.suggestedKind??(x.type==="counter_hypothesis"?"counter_hypothesis":"insight"),title:x.title,body:x.rationale,metadata:{proposal:true,proposalType:x.type,relatedIds:x.relatedIds},provenance:{origin:"system",actorId:"hypothesis-gardener",runId,createdAt:at,explanation:"Proposal only; never qualified knowledge"},createdAt:at,updatedAt:at,version:1}))}
