import type { EvidenceRecord, HypothesisProposal } from "../domain/types"
import type { SynthesisDefinition } from "./registry"
export type SynthesisFamily = "epistemics"|"customer_problem"|"jtbd_adoption"|"value_positioning"|"product_solution"|"pricing_economics"|"competition"|"distribution"|"trust_risk"|"experiment"|"narrative"|"strategy"|"emergent"
export interface FamilyOutput { statement:string; rationale:string; unknowns:string[]; suggestedResearch:string[]; hypotheses:HypothesisProposal[] }
export const familyForId=(id:string):SynthesisFamily=>{const n=Number(id.slice(1));return n<=10?"epistemics":n<=20?"customer_problem":n<=30?"jtbd_adoption":n<=40?"value_positioning":n<=50?"product_solution":n<=60?"pricing_economics":n<=70?"competition":n<=80?"distribution":n<=90?"trust_risk":n<=100?"experiment":n<=110?"narrative":n<=120?"strategy":"emergent"}
const top=(e:EvidenceRecord[],filter:(x:EvidenceRecord)=>boolean=()=>true)=>e.filter(filter).sort((a,b)=>b.strength-a.strength).slice(0,3).map(x=>x.claim)
const sourceDiversity=(e:EvidenceRecord[])=>new Set(e.map(x=>x.sourceId??x.sourceType)).size
export function runFamily(def:SynthesisDefinition,evidence:EvidenceRecord[],supportIds:string[],contradictionIds:string[]):FamilyOutput{
 const f=familyForId(def.id), claims=top(evidence), behavioral=top(evidence,e=>e.evidenceType==="behavioral"||e.evidenceType==="measured"), firstParty=top(evidence,e=>!!e.firstParty), contrad=evidence.filter(e=>contradictionIds.includes(e.id)).map(e=>e.claim), stated=top(evidence,e=>e.evidenceType==="stated"||!e.evidenceType)
 const unknowns:string[]=[];if(sourceDiversity(evidence)<2)unknowns.push("Independent source diversity is insufficient.");if(!behavioral.length)unknowns.push("No direct behavioral or measured evidence is present.");if(!firstParty.length)unknowns.push("No first-party evidence is present.")
 let rationale="",statement=""
 switch(f){
  case "epistemics": statement=`${def.name}: ${evidence.length} records across ${sourceDiversity(evidence)} independent source identities; ${contrad.length} contextual contradiction(s).`;rationale=`Strongest claims: ${claims.join(" | ")||"none"}. Confidence is bounded by freshness, independence, and behavioral coverage.`;break
  case "customer_problem": statement=`${def.name}: the recurring problem pattern is ${claims.join("; ")||"not yet evidenced"}.`;rationale=`Separate pain intensity, frequency, segment and downstream consequence before treating a topic as a problem.`;break
  case "jtbd_adoption": statement=`${def.name}: observed/stated workflow signals suggest ${[...behavioral,...stated].slice(0,3).join("; ")||"an unknown current workflow"}.`;rationale="Adoption depends on trigger, incumbent workaround, switching cost, and behavior-change burden.";break
  case "value_positioning": statement=`${def.name}: for the evidenced segment, promise an outcome tied to ${claims[0]??"the primary pain"}, against current alternatives, using customer language.`;rationale=`Mechanism must be supported; contextual contradictions: ${contrad.join("; ")||"none"}.`;break
  case "product_solution": statement=`${def.name}: the smallest solution should address ${claims[0]??"the core problem"} while avoiding unsupported feature scope.`;rationale="Feature requests are treated as solution hypotheses, not proof of value; workflow integration and dependencies remain explicit.";break
  case "pricing_economics": statement=`${def.name}: WTP remains a testable range anchored to alternative cost, urgency, current spend and behavioral payment evidence.`;rationale=`Behavioral/payment signals: ${behavioral.join("; ")||"none"}; stated signals: ${stated.join("; ")||"none"}.`;unknowns.push("A behavioral price test with explicit pass/fail threshold is required.");break
  case "competition": statement=`${def.name}: alternatives and substitutes should be compared on evidenced complaints, retained strengths, switching cost and incumbent response.`;rationale=`Evidence considered: ${claims.join("; ")||"none"}.`;break
  case "distribution": statement=`${def.name}: rank channels by reachable problem context and validation signal per cost, not audience size alone.`;rationale=`Current distribution signals: ${claims.join("; ")||"none"}.`;break
  case "trust_risk": statement=`${def.name}: adoption is gated by explicit trust, privacy, security, regulatory, platform and operational constraints.`;rationale=`Risk evidence: ${claims.join("; ")||"none"}; unknown risks stay unknown rather than inferred safe.`;break
  case "experiment": statement=`${def.name}: test the highest-impact uncertain assumption with an observable falsification threshold and cheapest credible method.`;rationale=`The test must discriminate predictions; current contradictions: ${contrad.join("; ")||"none"}.`;break
  case "narrative": statement=`${def.name}: communicate strongest findings, provenance, contradictions, confidence ceiling and unknowns without overstating causality.`;rationale=`Representative evidence: ${claims.join("; ")||"none"}.`;break
  case "strategy": statement=`${def.name}: allocate effort by evidence strength, uncertainty, impact, dependency and expected learning value.`;rationale=`Decision inputs: ${claims.join("; ")||"none"}; kill/scale thresholds must precede execution.`;break
  case "emergent": {const halves=[evidence.filter((_,i)=>i%2===0),evidence.filter((_,i)=>i%2===1)];statement=`${def.name}: ${halves[0][0]?.claim??"cluster A"} may connect to ${halves[1][0]?.claim??"cluster B"} through an untested dependency, tension or common cause.`;rationale="This is a graph-native proposal: bridge, second-order consequence, adjacent opportunity, venture boundary, or world-model change—not qualified knowledge.";break}
 }
 const proposal:HypothesisProposal={statement,title:def.name,hypothesisType:f,derivedFrom:evidence.map(e=>e.id),supportingEvidence:supportIds,contradictingEvidence:contradictionIds,strategicImportance:def.priority>=100?75:60,impact:60,uncertainty:70,rationale}
 return {statement,rationale,unknowns:[...new Set(unknowns)],suggestedResearch:[`Seek independent evidence that could falsify ${def.name}.`,behavioral.length?"Replicate behavioral evidence in another segment/source.":"Run a behavioral or measured test."],hypotheses:def.generatesHypotheses?[proposal]:[]}
}
