import type { ResearchResult, ResearchTask } from "../domain/types"
import { stableId } from "../domain/id"
export interface ResearchProviderPolicy { id:string; costClass:"local"|"free"|"free_quota"|"paid_optional"; requestsPerWindow?:number; windowSeconds?:number; concurrency:number; minIntervalMs?:number; enabled:boolean; health:"healthy"|"degraded"|"cooldown"|"disabled" }
export interface ResearchArtifact { title:string; excerpt:string; url?:string; publishedAt?:string; metadata?:Record<string,unknown> }
export interface ResearchProvider { policy:ResearchProviderPolicy; search(task:ResearchTask,signal?:AbortSignal):Promise<ResearchArtifact[]> }
abstract class HttpProvider implements ResearchProvider { abstract policy:ResearchProviderPolicy; abstract url(q:string):string; async search(task:ResearchTask,signal?:AbortSignal){if(!this.policy.enabled)return [];const r=await fetch(this.url(task.question),{signal,headers:{"User-Agent":"nodepad-research/1.0"}});if(!r.ok)throw new Error(`${this.policy.id}: HTTP ${r.status}`);return this.parse(await r.json())} abstract parse(v:any):ResearchArtifact[] }
export class HackerNewsProvider extends HttpProvider { policy={id:"hacker-news",costClass:"free" as const,requestsPerWindow:20,windowSeconds:60,concurrency:1,minIntervalMs:1000,enabled:true,health:"healthy" as const};url(q:string){return `https://hn.algolia.com/api/v1/search?tags=story&query=${encodeURIComponent(q)}`};parse(v:any){return (v.hits??[]).slice(0,10).map((x:any)=>({title:x.title||x.story_title,excerpt:x.comment_text||x.title||"",url:x.url||`https://news.ycombinator.com/item?id=${x.objectID}`,publishedAt:x.created_at,metadata:{points:x.points}}))} }
export class GitHubProvider extends HttpProvider { policy={id:"github",costClass:"free_quota" as const,requestsPerWindow:10,windowSeconds:60,concurrency:1,enabled:true,health:"healthy" as const};url(q:string){return `https://api.github.com/search/issues?q=${encodeURIComponent(q)}&per_page=10`};parse(v:any){return(v.items??[]).map((x:any)=>({title:x.title,excerpt:x.body?.slice(0,800)||"",url:x.html_url,publishedAt:x.created_at,metadata:{state:x.state,comments:x.comments}}))} }
export class WebSearchProvider implements ResearchProvider { policy={id:"web",costClass:"free" as const,concurrency:1,minIntervalMs:1500,enabled:true,health:"degraded" as const};constructor(private endpoint=process.env.NODEPAD_WEB_SEARCH_ENDPOINT){ }async search(task:ResearchTask,signal?:AbortSignal){if(!this.endpoint)return [];const r=await fetch(`${this.endpoint}?q=${encodeURIComponent(task.question)}`,{signal});if(!r.ok)throw new Error(`web: HTTP ${r.status}`);const v=await r.json() as any;return(v.results??[]).slice(0,10).map((x:any)=>({title:x.title,excerpt:x.body||x.snippet||"",url:x.href||x.url}))} }
export const defaultProviders=()=>[new HackerNewsProvider(),new GitHubProvider(),new WebSearchProvider()]
export async function executeResearch(task:ResearchTask,providers:ResearchProvider[]):Promise<ResearchResult[]>{const picked=providers.filter(p=>p.policy.enabled&&p.policy.health!=="disabled"&&(!task.preferredSources.length||task.preferredSources.includes(p.policy.id)));const settled=await Promise.allSettled(picked.map(async p=>(await p.search(task)).map(a=>({id:stableId("result",task.id,p.policy.id,a.url??a.title),taskId:task.id,providerId:p.policy.id,...a,retrievedAt:new Date().toISOString()}))));return settled.flatMap(x=>x.status==="fulfilled"?x.value:[])}
