import {spawn,type ChildProcessWithoutNullStreams} from "node:child_process"
import {mkdtemp,readFile,realpath,stat} from "node:fs/promises"
import {tmpdir} from "node:os"
import {dirname,join,resolve,sep} from "node:path"
import type {AgentProfile} from "../control-plane/types"
import type {CancelResult,ExecutionAdapter,ExecutionArtifact,ExecutionHealth,ExecutionRequest,ExternalRun,ExternalRunSnapshot,ExecutionStatus} from "../execution/types"

export type WorkingDirectoryPolicy="none"|"project_repository"|"isolated_temp"|"configured_root"
export interface CommandProfile {id:string;executable:string;args:string[];workingDirectoryPolicy:WorkingDirectoryPolicy;configuredRoot?:string;environmentAllowlist:string[];timeoutMs:number;killGraceMs:number;maxConcurrency:number}
export class CommandProfileRegistry {constructor(private profiles:CommandProfile[]){}static async fromEnvironment(){const file=process.env.NODEPAD_CLI_PROFILES_FILE;if(!file)throw new Error("CLI_PROFILES_NOT_CONFIGURED");const parsed=JSON.parse(await readFile(file,"utf8")) as {profiles?:CommandProfile[]};return new CommandProfileRegistry(parsed.profiles??[])}get(id:string){const profile=this.profiles.find(item=>item.id===id);if(!profile)throw new Error("CLI_COMMAND_PROFILE_NOT_FOUND");if(!profile.executable||!Array.isArray(profile.args)||!Array.isArray(profile.environmentAllowlist))throw new Error("CLI_COMMAND_PROFILE_INVALID");return profile}}
interface Owned {child:ChildProcessWithoutNullStreams;status:ExecutionStatus;providerStatus:string;artifacts:Omit<ExecutionArtifact,"id"|"delegationId"|"provider">[];diagnostic?:string;stderr:string;timer?:ReturnType<typeof setTimeout>;killTimer?:ReturnType<typeof setTimeout>}
const inside=(path:string,root:string)=>path===root||path.startsWith(`${root}${sep}`)
async function workingDirectory(profile:CommandProfile,request:ExecutionRequest){if(profile.workingDirectoryPolicy==="none")return undefined;if(profile.workingDirectoryPolicy==="isolated_temp")return mkdtemp(join(tmpdir(),"nodepad-agent-"));const candidate=profile.workingDirectoryPolicy==="project_repository"?request.providerConfig?.repositoryPath:profile.configuredRoot;if(typeof candidate!=="string")throw new Error("CLI_WORKING_DIRECTORY_REQUIRED");const canonical=await realpath(candidate),boundary=profile.configuredRoot?await realpath(profile.configuredRoot):canonical;if(!inside(canonical,boundary)||(await stat(canonical)).isDirectory()===false)throw new Error("CLI_WORKING_DIRECTORY_FORBIDDEN");return canonical}
export class LocalCliExecutionAdapter implements ExecutionAdapter {
  readonly adapterType="local_cli" as const;private owned=new Map<string,Owned>()
  constructor(private registry?:CommandProfileRegistry){}
  async health(profile:AgentProfile):Promise<ExecutionHealth>{try{await this.command(profile);return{status:"ready"}}catch(error){return{status:"disabled",message:error instanceof Error?error.message:"CLI unavailable"}}}
  async dispatch(request:ExecutionRequest):Promise<ExternalRun>{const command=await this.command(request.profile),active=[...this.owned.values()].filter(item=>["starting","running","waiting_for_human"].includes(item.status)).length;if(active>=command.maxConcurrency)throw new Error("CLI_CONCURRENCY_LIMIT");const cwd=await workingDirectory(command,request),env=Object.fromEntries(command.environmentAllowlist.filter(name=>process.env[name]!==undefined).map(name=>[name,process.env[name]!])) as unknown as NodeJS.ProcessEnv,child=spawn(command.executable,command.args,{shell:false,cwd,env,stdio:["pipe","pipe","pipe"]}) as ChildProcessWithoutNullStreams,externalRunId=globalThis.crypto.randomUUID(),state:Owned={child,status:"starting",providerStatus:"starting",artifacts:[],stderr:""};this.owned.set(externalRunId,state);child.stdout.setEncoding("utf8");child.stderr.setEncoding("utf8");let buffer="";child.stdout.on("data",(chunk:string)=>{buffer+=chunk;for(;;){const index=buffer.indexOf("\n");if(index<0)break;const line=buffer.slice(0,index);buffer=buffer.slice(index+1);this.message(state,line)}});child.stderr.on("data",(chunk:string)=>{state.stderr=`${state.stderr}${chunk}`.slice(-8_000)});child.once("error",(error:Error)=>{state.status="failed";state.providerStatus="spawn_error";state.diagnostic=error.message});child.once("exit",(code:number|null)=>{if(state.timer)clearTimeout(state.timer);if(state.killTimer)clearTimeout(state.killTimer);if(!["succeeded","failed","cancelled"].includes(state.status)){state.status=code===0?"succeeded":"failed";state.providerStatus=code===0?"exited":"exit_error";if(code!==0)state.diagnostic=state.stderr||`Process exited ${code}`}});state.timer=setTimeout(()=>{state.status="failed";state.providerStatus="timeout";state.diagnostic="CLI execution timed out";child.kill("SIGTERM");state.killTimer=setTimeout(()=>{if(child.exitCode===null)child.kill("SIGKILL")},command.killGraceMs)},command.timeoutMs);child.stdin.end(`${JSON.stringify({delegationId:request.delegationId,taskId:request.taskId,instruction:request.instruction,context:request.context})}\n`);const now=Date.now();return{id:externalRunId,delegationId:request.delegationId,provider:"local_cli",externalRunId,providerStatus:"starting",createdAt:now,updatedAt:now,startedAt:now,metadata:{commandProfileId:command.id,cwd:cwd??null}}}
  async reconcile(run:ExternalRun):Promise<ExternalRunSnapshot>{const state=this.owned.get(run.externalRunId);if(!state)return{externalRunId:run.externalRunId,status:"interrupted",providerStatus:"interrupted",diagnostic:"Nodepad no longer owns this local process"};return{externalRunId:run.externalRunId,status:state.status,providerStatus:state.providerStatus,artifacts:state.artifacts,diagnostic:state.diagnostic}}
  async cancel(run:ExternalRun):Promise<CancelResult>{const state=this.owned.get(run.externalRunId);if(!state)return{status:"unsupported",message:"CLI_PROCESS_NOT_OWNED"};if(["succeeded","failed","cancelled"].includes(state.status))return{status:state.status==="cancelled"?"cancelled":"unsupported"};state.status="cancelled";state.providerStatus="cancelled";state.child.kill("SIGTERM");return{status:"requested"}}
  async close(){for(const state of this.owned.values())if(state.child.exitCode===null)state.child.kill("SIGTERM");this.owned.clear()}
  private async command(profile:AgentProfile){const id=profile.config.commandProfileId;if(typeof id!=="string")throw new Error("CLI_COMMAND_PROFILE_REQUIRED");return(this.registry??=await CommandProfileRegistry.fromEnvironment()).get(id)}
  private message(state:Owned,line:string){let message:Record<string,unknown>;try{message=JSON.parse(line) as Record<string,unknown>}catch{state.status="failed";state.providerStatus="protocol_error";state.diagnostic="Invalid JSONL from local agent";return}if(message.type==="status"&&typeof message.status==="string"){state.providerStatus=message.status;state.status=message.status==="running"?"running":"starting"}else if(message.type==="needs_input"){state.status="waiting_for_human";state.providerStatus="needs_input";state.diagnostic=String(message.message??"").slice(0,1000)}else if(message.type==="artifact"&&message.artifact&&typeof message.artifact==="object"&&state.artifacts.length<100){const artifact=message.artifact as Record<string,unknown>;state.artifacts.push({type:["diff","file","document","report","log","url","other"].includes(String(artifact.type))?String(artifact.type) as ExecutionArtifact["type"]:"other",label:String(artifact.label??"Artifact").slice(0,300),externalRef:typeof artifact.externalRef==="string"?artifact.externalRef:undefined})}else if(message.type==="result"){state.status=message.status==="succeeded"?"succeeded":message.status==="cancelled"?"cancelled":"failed";state.providerStatus=String(message.status??"failed");state.diagnostic=typeof message.summary==="string"?message.summary.slice(0,1000):undefined}}
}
