import {describe,it} from "node:test"
import assert from "node:assert/strict"
import type {ControlPlaneState,RoutingContext} from "../control-plane/types"
import type {LayaDecisionProvider,LayaProviderResult} from "./provider"
import {LayaProviderError} from "./provider"
import {LayaRoutingService,type RoutingDecisionAudit} from "./decision-service"
const agent=(id:string)=>({id,name:id,adapterType:"http" as const,enabled:true,locality:"remote" as const,capabilities:["code" as const],maxConcurrency:1,config:{baseUrl:"https:\/\/x"},revision:1,createdAt:1,updatedAt:1})
const state=(n=2):ControlPlaneState=>({revision:4,agents:Array.from({length:n},(_,i)=>agent(String.fromCharCode(97+i))),rules:[],assignments:[],delegations:[]})
const config={provider:"remote_openai" as const,baseUrl:"https://laya.test/v1",model:"laya",requestTimeoutMs:100,maxConcurrentRequests:4,maxQueueSize:8,minConfidence:.7,minMargin:.15,maxCandidates:12}
class Fake implements LayaDecisionProvider{calls=0;constructor(private result:LayaProviderResult|Error){}async selectAgent(){this.calls++;if(this.result instanceof Error)throw this.result;return this.result}async health(){return{enabled:true,provider:"remote_openai" as const,reachable:true,configuredModel:"laya",state:"ready" as const}}}
const run=async(s:ControlPlaneState,p:Fake,c:RoutingContext={requiresCode:true})=>{const audits:RoutingDecisionAudit[]=[];const result=await new LayaRoutingService(p,config,{saveDecision:d=>audits.push(d)}).route(s,c);return{result,audits}}
describe("Laya routing service",()=>{
 it("bypasses remote Laya for one candidate, explicit assignments, and rule-fixed targets",async()=>{for(const s of [state(1),{...state(),assignments:[{id:"x",scope:"task" as const,scopeId:"t",agentProfileId:"a",role:"default" as const,createdAt:1,updatedAt:1}]},{...state(),rules:[{id:"r",name:"R",enabled:true,priority:1,match:{requiresCode:true},route:{agentProfileId:"a"},revision:1,createdAt:1,updatedAt:1}]}]){const p=new Fake({selectedAgentId:"b",probabilities:{a:.2,b:.8}}),{result,audits}=await run(s,p,{requiresCode:true,taskEntityId:"t"});assert.equal(p.calls,0);assert.equal(result.decision,"deterministic");assert.equal(audits.length,1);assert.deepEqual(result.probabilities,{})}})
 it("calls remote Laya only for unresolved candidates and applies confidence and margin",async()=>{for(const [probabilities,decision,reason] of [[{a:.8,b:.2},"selected",undefined],[{a:.6,b:.4},"escalate","low_confidence"],[{a:.575,b:.425},"escalate","low_confidence"],[{a:.7,b:.3},"selected",undefined]] as const){const p=new Fake({selectedAgentId:"a",probabilities}),{result}=await run(state(),p);assert.equal(p.calls,1);assert.equal(result.decision,decision);assert.equal(result.escalationReason,reason)}})
 it("uses inclusive exact thresholds and detects low margin independently",async()=>{const cfg={...config,minConfidence:.5,minMargin:.15},p=new Fake({selectedAgentId:"a",probabilities:{a:.575,b:.425}}),audits:RoutingDecisionAudit[]=[];const result=await new LayaRoutingService(p,cfg,{saveDecision:d=>audits.push(d)}).route(state(),{requiresCode:true});assert.equal(result.decision,"selected");assert.ok(Math.abs(result.margin!-.15)<1e-9);const low=new Fake({selectedAgentId:"a",probabilities:{a:.55,b:.45}});assert.equal((await new LayaRoutingService(low,cfg,{saveDecision(){}}).route(state(),{requiresCode:true})).escalationReason,"low_margin")})
 it("escalates provider failures and too many candidates without guessing",async()=>{const p=new Fake(new LayaProviderError("LAYA_TIMEOUT")),{result}=await run(state(),p);assert.equal(result.selectedAgentId,undefined);assert.equal(result.escalationReason,"laya_timeout");const many=new Fake({selectedAgentId:"a",probabilities:{a:1}}),r=await new LayaRoutingService(many,{...config,maxCandidates:2},{saveDecision(){}}).route(state(3),{requiresCode:true});assert.equal(many.calls,0);assert.equal(r.escalationReason,"too_many_candidates")})
})
