import type {AgentSelectionRequest,AgentSelectionResult,ControlPlaneState,LayaEscalationReason,RoutingContext} from "../control-plane/types"
import {evaluateRoutingPolicy} from "../control-plane/routing"
import type {LayaConfig} from "./config"
import {LayaProviderError,type LayaDecisionProvider} from "./provider"
export interface RoutingDecisionAudit extends AgentSelectionResult {taskEntityId?:string;projectEntityId?:string;controlPlaneRevision:number;remoteModelId?:string;createdAt:number}
export interface RoutingDecisionAuditWriter {saveDecision(decision:RoutingDecisionAudit):void}
const id=()=>globalThis.crypto?.randomUUID?.()??Math.random().toString(36).slice(2)
const reason=(code:string):LayaEscalationReason=>({LAYA_NOT_CONFIGURED:"laya_not_configured",LAYA_AUTH_FAILED:"laya_auth_failed",LAYA_UNAVAILABLE:"laya_unavailable",LAYA_BUSY:"laya_busy",LAYA_TIMEOUT:"laya_timeout",LAYA_INVALID_RESPONSE:"laya_invalid_response",LAYA_MODEL_NOT_FOUND:"laya_model_not_found",LAYA_RATE_LIMITED:"laya_rate_limited",PROBABILITY_DATA_UNAVAILABLE:"probability_data_unavailable"}[code] as LayaEscalationReason??"laya_unavailable")
export class LayaRoutingService {constructor(private provider:LayaDecisionProvider|null,private config:LayaConfig,private audit:RoutingDecisionAuditWriter){}async route(state:ControlPlaneState,context:RoutingContext):Promise<AgentSelectionResult>{const started=Date.now(),policy=evaluateRoutingPolicy(state,context),base={decisionId:id(),eligibleAgentIds:policy.eligibleAgentIds,probabilities:{},filteredAgents:policy.filteredAgents,matchedRuleIds:policy.matchedRuleIds,explicitAssignment:policy.explicitAssignment};let result:AgentSelectionResult;if(policy.explicitAssignment&&!policy.explicitAssignment.eligible)result={...base,decision:"escalate",decisionSource:"deterministic",escalationReason:"ineligible_explicit_assignment"};else if(policy.selectedAgentId)result={...base,selectedAgentId:policy.selectedAgentId,decision:"deterministic",decisionSource:"deterministic"};else if(!policy.eligibleAgentIds.length)result={...base,decision:"escalate",decisionSource:"deterministic",escalationReason:"no_eligible_agent"};else if(policy.eligibleAgentIds.length>this.config.maxCandidates)result={...base,decision:"escalate",decisionSource:"deterministic",escalationReason:"too_many_candidates"};else if(!this.provider)result={...base,decision:"unavailable",decisionSource:"laya",escalationReason:"laya_not_configured"};else{const candidates=Object.fromEntries(state.agents.filter(a=>policy.eligibleAgentIds.includes(a.id)).map(a=>[a.id,{name:a.name,description:a.description,locality:a.locality,capabilities:a.capabilities,privacyClass:a.privacyClass}]));const request:AgentSelectionRequest={routingContext:context,eligibleAgentIds:policy.eligibleAgentIds,candidates};try{const selected=await this.provider.selectAgent(request),values=Object.values(selected.probabilities).sort((a,b)=>b-a),confidence=selected.probabilities[selected.selectedAgentId],margin=confidence-(values[1]??0),epsilon=1e-12,lowConfidence=confidence+epsilon<this.config.minConfidence,lowMargin=margin+epsilon<this.config.minMargin;result={...base,selectedAgentId:lowConfidence||lowMargin?undefined:selected.selectedAgentId,probabilities:selected.probabilities,confidence,margin,decision:lowConfidence||lowMargin?"escalate":"selected",decisionSource:"laya",escalationReason:lowConfidence?"low_confidence":lowMargin?"low_margin":undefined,provider:{type:"remote_openai",model:selected.model??this.config.model}}}catch(e){const code=e instanceof LayaProviderError?e.code:"LAYA_UNAVAILABLE";result={...base,decision:"escalate",decisionSource:"laya",escalationReason:reason(code),retryAfter:e instanceof LayaProviderError?e.retryAfter:undefined,provider:{type:"remote_openai",model:this.config.model}}}}result.latencyMs=Date.now()-started;this.audit.saveDecision({...result,taskEntityId:context.taskEntityId,projectEntityId:context.projectEntityId,controlPlaneRevision:state.revision,remoteModelId:result.provider?.model,createdAt:Date.now()});return result}}
