import {describe,it} from "node:test"
import assert from "node:assert/strict"
import {LayaProviderError} from "./provider"
import {buildLayaRequest,parseOpenAILayaResponse,RemoteOpenAILayaProvider} from "./remote-openai-provider"
const ids=["a","b"],valid={choices:[{message:{content:JSON.stringify({selectedAgentId:"a",probabilities:{a:.8,b:.2}})}}],model:"laya-v1"}
const error=(fn:()=>unknown,code:string)=>assert.throws(fn,(e:unknown)=>e instanceof LayaProviderError&&e.code===code)
describe("remote OpenAI-compatible Laya provider",()=>{
 it("parses strict structured content and builds a compact request",()=>{assert.deepEqual(parseOpenAILayaResponse(valid,ids).probabilities,{a:.8,b:.2});const body=buildLayaRequest({routingContext:{title:"Edit workbook",requiresFileWrite:true},eligibleAgentIds:ids,candidates:{a:{name:"A",locality:"local",capabilities:["file_write"]},b:{name:"B",locality:"local",capabilities:["analysis"]}}},"laya");assert.equal(body.model,"laya");assert.doesNotMatch(JSON.stringify(body),/apiKey|workspace|note body/i)})
 it("rejects missing probabilities without inventing confidence",()=>error(()=>parseOpenAILayaResponse({selectedAgentId:"a"},ids),"PROBABILITY_DATA_UNAVAILABLE"))
 it("rejects unknown/omitted IDs, ineligible selection, bad values, sums, winners, malformed and empty responses",()=>{error(()=>parseOpenAILayaResponse({selectedAgentId:"c",probabilities:{a:.5,b:.5}},ids),"LAYA_INVALID_RESPONSE");error(()=>parseOpenAILayaResponse({selectedAgentId:"a",probabilities:{a:1}},ids),"LAYA_INVALID_RESPONSE");error(()=>parseOpenAILayaResponse({selectedAgentId:"a",probabilities:{a:2,b:-1}},ids),"LAYA_INVALID_RESPONSE");error(()=>parseOpenAILayaResponse({selectedAgentId:"a",probabilities:{a:.7,b:.7}},ids),"LAYA_INVALID_RESPONSE");error(()=>parseOpenAILayaResponse({selectedAgentId:"b",probabilities:{a:.8,b:.2}},ids),"LAYA_INVALID_RESPONSE");error(()=>parseOpenAILayaResponse({choices:[{message:{content:"not json"}}]},ids),"LAYA_INVALID_RESPONSE");error(()=>parseOpenAILayaResponse({choices:[]},ids),"LAYA_INVALID_RESPONSE")})
 it("maps HTTP failures, retries only 502/503 once, and never returns an arbitrary agent",async()=>{const config={provider:"remote_openai" as const,baseUrl:"https://laya.test/v1",model:"laya",requestTimeoutMs:100,maxConcurrentRequests:2,maxQueueSize:2,minConfidence:.7,minMargin:.15,maxCandidates:12},req={routingContext:{},eligibleAgentIds:ids,candidates:{a:{name:"A",locality:"local" as const,capabilities:[]},b:{name:"B",locality:"remote" as const,capabilities:[]}}};for(const [status,code] of [[401,"LAYA_AUTH_FAILED"],[404,"LAYA_MODEL_NOT_FOUND"],[429,"LAYA_RATE_LIMITED"],[500,"LAYA_UNAVAILABLE"]] as const){const provider=new RemoteOpenAILayaProvider(config,async()=>new Response("",{status}));await assert.rejects(provider.selectAgent(req),e=>e instanceof LayaProviderError&&e.code===code)}let calls=0;const provider=new RemoteOpenAILayaProvider(config,async()=>{calls++;return calls===1?new Response("",{status:502}):Response.json(valid)});assert.equal((await provider.selectAgent(req)).selectedAgentId,"a");assert.equal(calls,2)})
 it("maps aborts to timeout",async()=>{const config={provider:"remote_openai" as const,baseUrl:"https://laya.test/v1",model:"laya",requestTimeoutMs:10,maxConcurrentRequests:2,maxQueueSize:2,minConfidence:.7,minMargin:.15,maxCandidates:12};const provider=new RemoteOpenAILayaProvider(config,(_u,init)=>new Promise((_r,reject)=>init?.signal?.addEventListener("abort",()=>reject(new DOMException("aborted","AbortError")))));await assert.rejects(provider.selectAgent({routingContext:{},eligibleAgentIds:ids,candidates:{a:{name:"A",locality:"local",capabilities:[]},b:{name:"B",locality:"remote",capabilities:[]}}}),e=>e instanceof LayaProviderError&&e.code==="LAYA_TIMEOUT")})
 it("bounds concurrency without unbounded queueing",async()=>{const config={provider:"remote_openai" as const,baseUrl:"https://busy.test/v1",model:"laya",requestTimeoutMs:1000,maxConcurrentRequests:1,maxQueueSize:0,minConfidence:.7,minMargin:.15,maxCandidates:12};let release!:()=>void;const blocked=new Promise<void>(r=>release=r),provider=new RemoteOpenAILayaProvider(config,async()=>{await blocked;return Response.json(valid)}),req={routingContext:{},eligibleAgentIds:ids,candidates:{a:{name:"A",locality:"local" as const,capabilities:[]},b:{name:"B",locality:"remote" as const,capabilities:[]}}};const first=provider.selectAgent(req);await Promise.resolve();await assert.rejects(provider.selectAgent(req),e=>e instanceof LayaProviderError&&e.code==="LAYA_BUSY");release();assert.equal((await first).selectedAgentId,"a")})
})
