import type {AgentSelectionRequest} from "../control-plane/types"
import type {LayaConfig} from "./config"
import {openAIPath} from "./config"
import {LayaProviderError,type LayaDecisionProvider,type LayaProviderHealth,type LayaProviderResult} from "./provider"

class Gate {active=0;queue:Array<{resolve:()=>void;reject:(e:Error)=>void}>=[];constructor(private max:number,private queued:number){}async enter(){if(this.active<this.max){this.active++;return}if(this.queue.length>=this.queued)throw new LayaProviderError("LAYA_BUSY");await new Promise<void>((resolve,reject)=>this.queue.push({resolve,reject}));this.active++}leave(){this.active--;this.queue.shift()?.resolve()}}
const gates=new Map<string,Gate>()
const record=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v)
export function parseOpenAILayaResponse(raw:unknown,eligible:string[]):LayaProviderResult {let value:unknown=raw;if(record(raw)&&record(raw.decision))value=raw.decision;else if(record(raw)&&Array.isArray(raw.choices)){const content=(raw.choices[0] as {message?:{content?:unknown}}|undefined)?.message?.content;if(typeof content!=="string"||!content.trim())throw new LayaProviderError("LAYA_INVALID_RESPONSE");try{value=JSON.parse(content)}catch{throw new LayaProviderError("LAYA_INVALID_RESPONSE")}}if(!record(value)||typeof value.selectedAgentId!=="string")throw new LayaProviderError("LAYA_INVALID_RESPONSE");if(!record(value.probabilities))throw new LayaProviderError("PROBABILITY_DATA_UNAVAILABLE");if(!eligible.includes(value.selectedAgentId))throw new LayaProviderError("LAYA_INVALID_RESPONSE");const probabilities:Record<string,number>={};for(const [id,p] of Object.entries(value.probabilities)){if(!eligible.includes(id)||typeof p!=="number"||!Number.isFinite(p)||p<0||p>1)throw new LayaProviderError("LAYA_INVALID_RESPONSE");probabilities[id]=p}if(Object.keys(probabilities).length!==eligible.length||eligible.some(id=>!(id in probabilities)))throw new LayaProviderError("LAYA_INVALID_RESPONSE");const sum=Object.values(probabilities).reduce((a,b)=>a+b,0);if(Math.abs(sum-1)>.01)throw new LayaProviderError("LAYA_INVALID_RESPONSE");const sorted=Object.entries(probabilities).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));if(sorted[0]?.[0]!==value.selectedAgentId)throw new LayaProviderError("LAYA_INVALID_RESPONSE");return{selectedAgentId:value.selectedAgentId,probabilities,model:record(raw)&&typeof raw.model==="string"?raw.model:undefined,metadata:record(value.metadata)?value.metadata:undefined}}
export function buildLayaRequest(request:AgentSelectionRequest,model:string){const c=request.routingContext;return{model,temperature:0,response_format:{type:"json_object"},messages:[{role:"system",content:"Select exactly one eligible agent. Return JSON with selectedAgentId and a calibrated probabilities object covering every candidate; probabilities must sum to 1."},{role:"user",content:JSON.stringify({routingContext:{workType:c.workType,title:c.title,hasFiles:c.hasFiles,requiresFileRead:c.requiresFileRead,requiresFileWrite:c.requiresFileWrite,requiresWeb:c.requiresWeb,requiresCode:c.requiresCode,privacyClass:c.privacyClass,localityRequirement:c.localityRequirement,labels:c.labels,requiredCapabilities:c.requiredCapabilities},candidates:request.candidates})}]}}
export class RemoteOpenAILayaProvider implements LayaDecisionProvider {private gate:Gate;constructor(private config:LayaConfig,private fetcher:typeof fetch=fetch){const key=`${config.baseUrl}:${config.maxConcurrentRequests}:${config.maxQueueSize}`;this.gate=gates.get(key)??new Gate(config.maxConcurrentRequests,config.maxQueueSize);gates.set(key,this.gate)}async selectAgent(request:AgentSelectionRequest){await this.gate.enter();try{return await this.perform(request)}finally{this.gate.leave()}}private async perform(request:AgentSelectionRequest){for(let attempt=0;attempt<2;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.config.requestTimeoutMs);try{const response=await this.fetcher(openAIPath(this.config.baseUrl,"chat/completions"),{method:"POST",headers:{"content-type":"application/json",...(this.config.apiKey&&{authorization:`Bearer ${this.config.apiKey}`})},body:JSON.stringify(buildLayaRequest(request,this.config.model)),signal:controller.signal});if((response.status===502||response.status===503)&&attempt===0)continue;if(response.status===401||response.status===403)throw new LayaProviderError("LAYA_AUTH_FAILED");if(response.status===404)throw new LayaProviderError("LAYA_MODEL_NOT_FOUND");if(response.status===429)throw new LayaProviderError("LAYA_RATE_LIMITED",response.headers.get("retry-after")??undefined);if(!response.ok)throw new LayaProviderError("LAYA_UNAVAILABLE");let body:unknown;try{body=await response.json()}catch{throw new LayaProviderError("LAYA_INVALID_RESPONSE")}return parseOpenAILayaResponse(body,request.eligibleAgentIds)}catch(e){if(e instanceof LayaProviderError)throw e;if((e as Error).name==="AbortError")throw new LayaProviderError("LAYA_TIMEOUT");throw new LayaProviderError("LAYA_UNAVAILABLE")}finally{clearTimeout(timer)}}throw new LayaProviderError("LAYA_UNAVAILABLE")}async health():Promise<LayaProviderHealth>{try{const r=await this.fetcher(openAIPath(this.config.baseUrl,"models"),{headers:{...(this.config.apiKey&&{authorization:`Bearer ${this.config.apiKey}`})},signal:AbortSignal.timeout(this.config.requestTimeoutMs)});if(!r.ok)return{enabled:true,provider:"remote_openai",reachable:false,configuredModel:this.config.model,state:r.status===404?"model_not_found":"unavailable"};const body=await r.json() as {data?:{id?:string}[]};const found=body.data?.some(x=>x.id===this.config.model)??true;return{enabled:true,provider:"remote_openai",reachable:true,configuredModel:this.config.model,state:found?"ready":"model_not_found"}}catch{return{enabled:true,provider:"remote_openai",reachable:false,configuredModel:this.config.model,state:"unavailable"}}}}
