import { mkdir, readFile, rm, writeFile } from "node:fs/promises"
import path from "node:path"
import { execFile } from "node:child_process"
import { promisify } from "node:util"
import type { Workspace } from "../domain/types"
import type { NodepadStore } from "../persistence/store"
import { restoreSerialized, serializeWorkspace, type SerializedWorkspace } from "./serialization"
const exec=promisify(execFile)
export interface BackupRemote { status():Promise<{configured:boolean;detail:string}>;pushWorkspace(snapshot:SerializedWorkspace):Promise<{commitSha:string;skipped?:boolean}>;listSnapshots(workspaceId:string):Promise<{ref:string}[]>;restoreWorkspace(workspaceId:string,ref:string):Promise<SerializedWorkspace> }
export class LocalGitBackup implements BackupRemote { constructor(private repo=process.env.NODEPAD_BACKUP_REPO||path.join(process.cwd(),"data","backups"),private base=process.env.NODEPAD_GITHUB_PATH||"nodepad-workspaces"){}async status(){return{configured:true,detail:this.repo}};async pushWorkspace(s:SerializedWorkspace){await mkdir(this.repo,{recursive:true});try{await exec("git",["init","-q"],{cwd:this.repo})}catch{};const root=path.join(this.repo,this.base,s.workspaceId);await rm(root,{recursive:true,force:true});for(const [name,value] of Object.entries(s.files)){const f=path.join(root,name);await mkdir(path.dirname(f),{recursive:true});await writeFile(f,value)}await exec("git",["add","--",this.base],{cwd:this.repo});const diff=await exec("git",["diff","--cached","--quiet"],{cwd:this.repo}).then(()=>false).catch(()=>true);if(!diff)return{commitSha:(await exec("git",["rev-parse","HEAD"],{cwd:this.repo})).stdout.trim(),skipped:true};await exec("git",["-c","user.name=Nodepad","-c","user.email=nodepad@localhost","commit","-m",`nodepad(${s.workspaceId}): backup`],{cwd:this.repo});return{commitSha:(await exec("git",["rev-parse","HEAD"],{cwd:this.repo})).stdout.trim()}}async listSnapshots(){try{return(await exec("git",["log","--format=%H"],{cwd:this.repo})).stdout.trim().split("\n").filter(Boolean).map(ref=>({ref}))}catch{return[]}}async restoreWorkspace(id:string,ref:string):Promise<SerializedWorkspace>{const files=(await exec("git",["ls-tree","-r","--name-only",ref,"--",`${this.base}/${id}`],{cwd:this.repo})).stdout.trim().split("\n").filter(Boolean);const out:Record<string,string>={};for(const f of files)out[path.relative(path.join(this.base,id),f)]=(await exec("git",["show",`${ref}:${f}`],{cwd:this.repo,maxBuffer:20_000_000})).stdout;return{workspaceId:id,schemaVersion:1,files:out}}}
export async function backupWorkspace(w:Workspace,remote:BackupRemote=new LocalGitBackup()){const min=Number(process.env.NODEPAD_GITHUB_MIN_COMMIT_INTERVAL_SECONDS??600)*1000;if(w.backup?.lastBackupAt&&Date.now()-Date.parse(w.backup.lastBackupAt)<min)return{commitSha:w.backup.lastCommitSha??"debounced",skipped:true};const snap=serializeWorkspace(w);return remote.pushWorkspace(snap)}
export async function stageRestore(store:NodepadStore,remote:BackupRemote,id:string,ref:string,newId=`${id}-restored-${Date.now()}`){const snap=await remote.restoreWorkspace(id,ref);const staged=restoreSerialized(snap,newId);await store.saveWorkspace(staged);return staged}
